### ISSUE TITLE
Instagram changed it's API. Undefined index: user

### ISSUE THREAD

**Issue by jannejava** [pgrimaud/instagram-user-feed#1]
First thanks, for making this package!

The package has been working great, but yesterday I noticed that it's no longer returning images from Instagram. After some digging I found this. It seems like Instagram has changed it's API: https://elfsight.com/blog/2018/02/instagram-graph-api-changes/

**Comment by pgrimaud** [comment]
Fixed in 2.0 : https://github.com/pgrimaud/instagram-user-feed/releases/tag/2.0.0

Thanks for your PR
