### ISSUE TITLE
Impossible to login with 2FAC account

### ISSUE THREAD

**Issue by Ladylain** [pgrimaud/instagram-user-feed#109]
**Version(s) affected**: 6.3

**Description**  
Hello, 
I have a little issue, with my account, i can't log in to it cause i have a 2 factor verification. 
Is there a way that i could log in with this API easily ? 

Best

**Comment by pgrimaud** [comment]
Hello @Ladylain,

I'm you're using a 2 factor authentication, I guess you're using a personal Instagram account, right?

This library is using scrapping to retrieve data from Instagram, so I suggest to you to create a new instagram account to use this package.

**Comment by vietel** [comment]
Agreed with @pgrimaud
If you @Ladylain, only log in to scrapping data from other accounts. You just need any normal account, no need to turn on two-factor authentication on that account
