### ISSUE TITLE
Fatal Error Uncaught TypeError: Argument 1 passed to Instagram\Api::

### ISSUE THREAD

**Issue by filippodicostanzo** [pgrimaud/instagram-user-feed#111]
**Version(s) affected**: 6.3.1

**Description**  
`Fatal error: Uncaught TypeError: Argument 1 passed to Instagram\Api::__construct() must be an instance of Instagram\Storage\CacheManager, instance of Symfony\Component\Cache\Adapter\FilesystemAdapter given, called in Y:\php.localidautore.it\instagram-user-feed\index.php on line 29 and defined in Y:\php.localidautore.it\instagram-user-feed\vendor\pgrimaud\instagram-user-feed\src\Instagram\Api.php:44`

**How to reproduce**  
```
use Instagram\Api;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');
$api = new Api($cachePool);
$api->login('username', 'password'); // mandatory
$profile = $api->getProfile('robertdowneyjr');

echo $profile->getUserName(); // robertdowneyjr
echo $profile->getFullName(); // Robert Downey Jr. Official
```

**Comment by pgrimaud** [comment]
Hello @filippodicostanzo 

This error `Fatal error: Uncaught TypeError: Argument 1 passed to Instagram\Api::__construct() must be an instance of Instagram\Storage\CacheManager` seems to be linked to old library ^5.x.

https://github.com/pgrimaud/instagram-user-feed/blob/5.6/src/Instagram/Api.php#L44

Could you : 

- Try check the correct version of this lib in your composer.json / composer.lock files
- Remove your vendor folder
- Execute composer install
- Then retry

😄

**Comment by hosseind600** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to Instagram\Api::__construct() must be an instance of Instagram\Storage\CacheManager or null, instance of Symfony\Component\Cache\Adapter\FilesystemAdapter given, called in C:\xamppp\htdocs\test.php on line 16 and defined in C:\xamppp\htdocs\vendor\pgrimaud\instagram-user-feed\src\Instagram\Api.php:44 Stack trace: #0 C:\xamppp\htdocs\test.php(16): Instagram\Api->__construct(Object(Symfony\Component\Cache\Adapter\FilesystemAdapter)) #1 {main} thrown in C:\xamppp\htdocs\vendor\pgrimaud\instagram-user-feed\src\Instagram\Api.php on line 44

**test.php**
`
<?php
declare(strict_types=1);

use Instagram\Api;
use Instagram\Exception\InstagramException;

use Instagram\Model\User;
use Psr\Cache\CacheException;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

require './vendor/autoload.php';

$cachePool = new FilesystemAdapter('Instagram', 0, './cache');

try {
    $api = new Api($cachePool);
    $api->login("xxx", "cccc");
...
...
...
`
