### ISSUE TITLE
Class FilesystemAdapter not found

### ISSUE THREAD

**Issue by webair-studio** [pgrimaud/instagram-user-feed#112]
**Version(s) affected**: 6.3.2

**Description**  
Fatal error: Uncaught Error: Class 'Symfony\Component\Cache\Adapter\FilesystemAdapter' not found in /home/mydir/public_html/instagram/examples/profile.php:14 Stack trace: #0 {main} thrown in /home/mydir/public_html/instagram/examples/profile.php on line 14

I installed `composer require cache/filesystem-adapter`, but it didn't work for me. 
/vendor/cache/filesystem-adapter/  - exist. Maybe connect it manually?

**Comment by pgrimaud** [comment]
The exact package for cache is `symfony/cache` : (https://github.com/pgrimaud/instagram-user-feed/blob/master/composer.json#L43)

I should be installed automatically if you made a `composer require pgrimaud/instagram-user-feed`

I guess you could try `composer require symfony/cache` and try again

**Comment by webair-studio** [comment]
`composer require symfony/cache` - installed, ok.
New error: 
`Fatal error: Uncaught TypeError: Argument 1 passed to Instagram\Api::__construct() must be an instance of Instagram\Storage\CacheManager or null, instance of Symfony\Component\Cache\Adapter\FilesystemAdapter given, called in /home/mydir/public_html/instagram/examples/profile.php on line 17 and defined in /home/mydir/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php:44 Stack trace: #0 /home/mydir/public_html/instagram/examples/profile.php(17): Instagram\Api->__construct(Object(Symfony\Component\Cache\Adapter\FilesystemAdapter)) #1 {main} thrown in /home/mydir/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php on line 44`

Can you put the distribution kit into the repository without composer?...

**Comment by pgrimaud** [comment]
This is another error. Weird, you got the same error as #111...
Can you past the code where you declare `new Instagram\Api();` and which trigger this error?

**Comment by webair-studio** [comment]
`Fatal error: Uncaught Error: Call to a member function getLastInstagramEmailContent() on null in /home/mydir/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php:134 Stack trace: #0 /home/mydir/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php(94): Instagram\Auth\Login->checkpointChallenge(Object(GuzzleHttp\Cookie\CookieJar), Object(stdClass)) #1 /home/mydir/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(79): Instagram\Auth\Login->process() #2 /home/mydir/public_html/instagram/examples/profile.php(18): Instagram\Api->login('MyInsta', 'Mypass') #3 {main} thrown in /home/mydir/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php on line 134`

`('MyInsta', 'Mypass', 'imap.yandex.ru:993/imap/ssl', 'info@site.com', 'Mypass')` - credentails.php


Instagram does not send a letter, did I understand correctly?

Instagram asks if I visited it or not. The letter does not send. Screenshot:
![2020-07-16_230113](https://user-images.githubusercontent.com/18102692/87717038-6e7fca80-c7b8-11ea-8e83-0f3f3df4dada.jpg)

**Comment by pgrimaud** [comment]
Damn, I never seen this challenge before. 
Is it an old or a fresh Instagram account? Created before 1st may 2020?

**Comment by webair-studio** [comment]
This is my personal account, created in 2018. The challenge appears after I run the script. It looks like this is new against parsing. The "This is me" button can only be clicked with js, right? I press it manually, but the script doesn't work. Hmm ... I'll have to use the official api.

Or is it possible to copy cookies from my browser? ...

**Comment by pgrimaud** [comment]
I wrote on the README.md : 

 > Tips: you just have to create or use a dummy account to use easily this package.

If you create a new Instagram account, just to use this package it will work without any problem.

**Comment by PrasadBroo** [comment]
hey im late i fixed this with one line of code just require it on top

` requuire  'vendor/autoload.php' `

**Comment by GregDG** [comment]
Hello, I got the same problem with : 
- vendor/autoload on top
- dummy account (today)
- correct version on composer.json / composer.lock
- removed vendor folder then tried "composer install" again (like it is said in [#111](https://github.com/pgrimaud/instagram-user-feed/issues/111#issuecomment-659056214))

Error message : 
`Fatal error: Uncaught TypeError: Argument 1 passed to Instagram\Api::__construct() must be an instance of Instagram\Storage\CacheManager or null, instance of Symfony\Component\Cache\Adapter\FilesystemAdapter given, called in E:\MonDossier\web\test.php on line 17 and defined in E:\MonDossier\web\vendor\pgrimaud\instagram-user-feed\src\Instagram\Api.php:44 Stack trace: #0 E:\MonDossier\web\test.php(17): Instagram\Api->__construct(Object(Symfony\Component\Cache\Adapter\FilesystemAdapter)) #1 {main} thrown in E:\MonDossier\web\vendor\pgrimaud\instagram-user-feed\src\Instagram\Api.php on line 44`

Available by email/phone(FR) too, in order to solve this !

Regards,
Greg

**Comment by pgrimaud** [comment]
Hello @GregDG 

Could you paste the code of your file test.php?

**Comment by GregDG** [comment]
This is the code in Usage section on the homepage : 
```
<?
require "vendor/autoload.php";

use Instagram\Api;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');

$api = new Api($cachePool);
$api->login('monlogin', 'monmdp');

$profile = $api->getProfile('robertdowneyjr');

print_r($profile);
?>
```

**Comment by pgrimaud** [comment]
Could you call me on Discord (Nilzen#5130)? It will be easier

**Comment by GregDG** [comment]
Done !

**Comment by jolsebastian** [comment]
What happened? Was this solved yet? I have sort of the same issues
