### ISSUE TITLE
Undefined Constant METADATA_TAGS AbstractAdapter

### ISSUE THREAD

**Issue by prdt3e** [pgrimaud/instagram-user-feed#113]
Undefined Constant METADATA_TAGS AbstractAdapter.php

Installation: Composer
Symfony: 5.1

**Comment by pgrimaud** [comment]
Do you have not details about error?
Line, file, stack trace e.g.?

**Comment by prdt3e** [comment]
Achso, thought that is unnecessary, since the query occurs only once in the AbstractAdapter.
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php (83)

**Comment by prdt3e** [comment]
I commented it out from Symfony, then everything went smoothly.
No solution, but quick.
