### ISSUE TITLE
Cannot serialize Symfony\Component\Cache\Adapter\FilesystemAdapter

### ISSUE THREAD

**Issue by haigooner95** [pgrimaud/instagram-user-feed#115]
$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');

$api = new Api($cachePool);
$api->login('username', 'password'); // mandatory

When i pass $api to a queue job and dispatch it (in Laravel), return this error

Please help me to resolve it, i need to scrape many instagram accounts with with once log in session

**Comment by pgrimaud** [comment]
What is the error?

**Comment by haigooner95** [comment]
> What is the error?

Have you ever used queue job in laravel?
When i send $api to job and dispatch it, it return error : "Cannot serialize Symfony\Component\Cache\Adapter\FilesystemAdapter"

**Comment by pgrimaud** [comment]
I think you should send to your queue job only the username to scrape and no php objects.

Then your worker which read jobs todo will start scrapping and init scrapping objects (cache pool and instagram api).
