### ISSUE TITLE
Allow POP3 on the checkpoint challenge bypass

### ISSUE THREAD

**Issue by gtapps** [pgrimaud/instagram-user-feed#118]
Hello!

If possible can we add pop3 on the imap_open function on the checkpoint challenge bypass?

Thank you!
G

**Comment by pgrimaud** [comment]
Yeah thanks, did you try with a real POP3 account?

**Comment by gtapps** [comment]
Yes I did, it worked fine.

Cheers,

Pierre Grimaud <notifications@github.com> escreveu em ter, 18/08/2020 às
13:49 :

**Comment by pgrimaud** [comment]
Thanks for your contribution 😄
