### ISSUE TITLE
Using with Laravel 5.8, Undefined property: stdClass::$authenticated error

### ISSUE THREAD

**Issue by pwnz22** [pgrimaud/instagram-user-feed#121]
**Version(s) affected**: 6.3

**Description**  
Getting error ```Undefined property: stdClass::$authenticated```. Using this package with Laravel 5.8. 
```
$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');
$api = new Api($cachePool);
$api->login('pwnzov', '*****'); // mandatory
$profile = $api->getProfile('mosarch.buro');
$medias = $profile->getMedias()
```

**How to reproduce**  
Here i reproducing it: **https://мосарх.рф/instagram**

**Possible Solution**  
Optional: only if you have suggestions on a fix/reason for the bug

**Additional context**  
```
/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php Line 103

 if ($response->authenticated == true) {
```
https://imgur.com/AmA9too

On the local environment it's working fine.

**Comment by pgrimaud** [comment]
Hello @pwnz22 

Could you dump the value of `$response` line 101?

**Comment by pwnz22** [comment]
Hi @pgrimaud 

```
{#716 ▼
  +"errors": {#718 ▼
    +"error": array:1 [▼
      0 => "Sorry, there was a problem with your request."
    ]
  }
  +"status": "ok"
  +"error_type": "generic_request_error"
}
```

**Comment by pgrimaud** [comment]
Unfortunately, you IP is probably ban from Instagram. You're using a shared hosting right?

If you try with a proxy, it should work properly.

(Example of proxy usage here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/using-proxies.php#L17)

**Comment by pwnz22** [comment]
```
'https' => '91.209.25.156:8080'

Tell please what's the IP i must put here?!

**Comment by pgrimaud** [comment]
It was a dummy IP taken from http://free-proxy.cz/en/

⚠️ But take care of using free proxy, network is probably sniffed and people can retrieve your account details and/or cookies associated. 

You also can buy one from [https://proxy6.net/en](https://proxy6.net/en/?r=128583), which offers good services.

**Comment by pwnz22** [comment]
I'm getting error with proxy also
```
Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response: {"message": "", "spam": true, "status": "fail"} 
```

**Comment by pwnz22** [comment]
Even with proxy cant get it work
```
Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response: {"message": "", "spam": true, "status": "fail"} 
```
Now getting this error. Also added checkpoint challenge with imap :(

**Comment by pgrimaud** [comment]
Did you use a free or a private proxy?

Unfortunately, free proxies are always blacklisted from Instagram.

**Comment by pwnz22** [comment]
Now i'm using free proxy. Understand problem. Thanks.

**Comment by smknstd** [comment]
I get this error, so IP from my digital ocean VPS is probably banned:

```
Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response: {\"message\": \"\", \"spam\": true, \"status\": \"fail\"}
```
