### ISSUE TITLE
Exception if Instagram ask for phone verification

### ISSUE THREAD

**Issue by Tutt-J** [pgrimaud/instagram-user-feed#125]
**Version(s) affected**: x.y.z

**Description**  
I don't why but each week instagram account block and ask me to verify my identity with my phone. But at this moment, the bundle make a fetch exception which litteraly crash website.

**How to reproduce**  
Hard to reproduce, cause it depends of instagram

**Comment by pgrimaud** [comment]
Hello @Tutt-J 

Are you using a real Instagram account? Or a dummy and dedicated Instagram account to use this app?

> But at this moment, the bundle make a fetch exception which litteraly crash website.

You could handle it with a try / catch, time to find a solution 😄

**Comment by Tutt-J** [comment]
Hello,

I use a real Instagram account. Yes I can handle it bu can you give me an example because i tried a lot of thing without success...

**Comment by pgrimaud** [comment]
> I use a real Instagram account. 

I think you should try to use a dedicated new account for your website, created from a desktop browser.


> Yes I can handle it bu can you give me an example because i tried a lot of thing without success...

Which exception is triggered?

**Comment by Tutt-J** [comment]
Yes my account was created on a desktop browser...

It's the fetch exception

**Comment by pgrimaud** [comment]
> Yes my account was created on a desktop browser...

Why Instagram ask you to verify your identity with your phone? Did you connect this account to your Instagram phone app?

> It's the fetch exception

If it's an InstagramFetchException, you could handle it this a try/catch like in this example : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/profile.php#L38

```php
try {
    ...
    $api     = new Api($cachePool);
    $api->login($credentials->getLogin(), $credentials->getPassword());

    $profile = $api->getProfile('robertdowneyjr');
    ...
} catch (InstagramException $e) {
}
```
