### ISSUE TITLE
CheckpointChallenge Trying to get property 'content' of non-object

### ISSUE THREAD

**Issue by thevanak** [pgrimaud/instagram-user-feed#126]
**Version(s) affected**: 6.4

**Description**  
Simply get stuck in function called SendSecurityCode in pgrimaud\instagram-user-feed\src\Instagram\Auth\Checkpoint\Challenge.php:91

**How to reproduce**  
When I try to login with account, what require checkpoint challenge.

**Additional context**  
I am using Laravel, I dont know if its something important.

**Comment by pgrimaud** [comment]
Hi, sorry about the delay.

Could you give me more details about the error.
Did you get a timeout or something else?
