### ISSUE TITLE
should email authentication work with outlook emails?

### ISSUE THREAD

**Issue by l-uke** [pgrimaud/instagram-user-feed#127]
Hi,
I am testing the getLastInstagramEmailContent function of ImapClient.php.
When checking my outlook email it says 
`Notice: Undefined property: stdClass::$senderaddress`
indeed there is no senderaddress header shown. Should I just edit this this to search for the correct header or am I doing somthing wrong ?
Thanks for this awesome project.

**Comment by pgrimaud** [comment]
Hello @l-uke 

It's seems you're connected to your mail box using imap. This lib will check mails in MAILBOX folder and it seems there's an email without senderaddress (weird).

Could you dump value of `$headers` this line https://github.com/pgrimaud/instagram-user-feed/blob/master/src/Instagram/Auth/Checkpoint/ImapClient.php#L117 ?

**Comment by l-uke** [comment]
{"date":"Wed, 2 Sep 2020 17:42:07 +0000","Date":"Wed, 2 Sep 2020 17:42:07 +0000","subject":"263104 is your Instagram code","Subject":"263104 is your Instagram code","message_id":"<9f01fc4aed4311eaa8e6b02628a0d9ca-9ddaba70@d5270c9cdb1aeb272bde795d9fed4797bb67ee0a786f58e0b30c2b183f9de4df>","toaddress":"verna12264243@outlook.com","to":[{"mailbox":"verna12264243","host":"outlook.com"}],"fromaddress":"Instagram ","from":[{"personal":"Instagram","mailbox":"no-reply","host":"mail.instagram.com"}],"reply_toaddress":"Instagram ","reply_to":[{"personal":"Instagram","mailbox":"no-reply","host":"mail.instagram.com"}],"Recent":" ","Unseen":" ","Flagged":" ","Answered":" ","Deleted":" ","Draft":" ","Msgno":" 2","MailDate":" 3-Sep-2020 03:42:18 +1000","Size":"52792","udate":1599068538}

**Comment by pgrimaud** [comment]
Hi @l-uke 

I release a new version with support of outlook email (6.4.3)
