### ISSUE TITLE
Smaller thumbnailSrc sizes

### ISSUE THREAD

**Issue by palicko** [pgrimaud/instagram-user-feed#13]
Hi,
is there any way to get smaller thumbnailSrc size (150x150 or 240x240) instead of current 640x640?
I am using v5.0.

Thanks

**Comment by pgrimaud** [comment]
Hi @palicko,

Please upgrade to [v5.1](https://github.com/pgrimaud/instagram-user-feed/releases/tag/5.1.0).
I added all thumbnails as array in media object.

Regards
