### ISSUE TITLE
Sometimes I get this error

### ISSUE THREAD

**Issue by l-uke** [pgrimaud/instagram-user-feed#130]
Notice: Trying to get property 'content' of non-object in /var/www/html/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Checkpoint/Challenge.php on line 91

Warning: Invalid argument supplied for foreach() in /var/www/html/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Checkpoint/Challenge.php on line 91

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://www.instagram.com/challenge/40973464118/pEBwlrMKvJ/` resulted in a `400 Bad Request` response: {"message": "", "challenge": {"challengeType": "RecaptchaChallengeForm", "errors": ["The captcha solution was not correc (truncated...) in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111 Stack trace: #0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/html/vendor/ in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111

**Comment by pgrimaud** [comment]
It often append when email from Instagram is a little lit slow. The login script will retrieve an old email from Instagram an extract an outdated security code.

How many login did you perform with this app per day/account? With the cache manager, you should only authenticate an account 1 time, for a long time.
