### ISSUE TITLE
if I use an incorrect profile in the example  profile.php I get this error 

### ISSUE THREAD

**Issue by l-uke** [pgrimaud/instagram-user-feed#131]
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.instagram.com/kjshdfkjdshfkjd/` resulted in a `404 Not Found` response: <!DOCTYPE html> <html lang="en" class="no-js logged-in client-root"> <head> <meta charset="utf-8"> < (truncated...) in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111 Stack trace: #0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/html/vendor/guzzlehttp/promises/ in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111

**Comment by pgrimaud** [comment]
Hi, you can now handle this error this `InstagramException`.
You could try examples/profile.php with an invalid username.
