### ISSUE TITLE
Unable to extract JSON data

### ISSUE THREAD

**Issue by crgAdrian** [pgrimaud/instagram-user-feed#132]
I've been getting this error for a few hours.

vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php:53

**Comment by pgrimaud** [comment]
Could you give me the complete error?

**Comment by crgAdrian** [comment]
https://gyazo.com/a6439c2bb407f3854d11c39b6b6ab0ab

**Comment by crgAdrian** [comment]
POSIBLE:

The problem was when google asking a confirmation for location, security stuff.....

How I fixed "for now":

1. Deleting *cache folder* generated.
2. Confirm location Google (this was me)
3. Confirm location Instagram  (this was me)

**Comment by talhamubashar0012** [comment]
Hi there, I'm facing the same issue on my dev server and the above mentioned fixes are not working for me as well

**Comment by aroy314** [comment]
I'm experiencing the same issue on my production server, and being spammed on my Instagram Account to "confirm this was me"

**Comment by chOse** [comment]
Exact same error for me today.

**Comment by gtapps** [comment]
Same for me.

**Comment by gtapps** [comment]
My problem was because my account got blocked for suspicious activity, I guess it's because of the crawling, IG must have implemented a check, basically all you have to do is relogin into your IG account and change your PW.

**Comment by paulprins** [comment]
I had this too and needed to open that account in instagram to verify that it was me logging in.

**Comment by MehdiMJ1** [comment]
I had the same problem and I have fixed now , it caused by detecting a **suspicious activity in your account**, so you must identify your entity by solving **Captcha** and **sending security code by phone number**,  that it is , just enter the official **Instagram** app and do these steps ..
My Pleasure To Help You 😁.

**Comment by talhamubashar0012** [comment]
> I had the same problem and I have fixed now , it caused by detecting a **suspicious activity in your account**, so you must identify your entity by solving **Captcha** and **sending security code by phone number**, that it is , just enter the official **Instagram** app and do these steps ..
> My Pleasure To Help You 😁.

None of this worked for me. Tried several time to verify but its not working. Does anyone of you guys have a better solution. It will be helpful

**Comment by PrasadBroo** [comment]
im also facing same problem on production server

**Comment by pgrimaud** [comment]
@PrasadBroo could contact me on Twitter by DM to try to find a solution? https://twitter.com/pgrimaud_

**Comment by curruwilla** [comment]
Unable to extract JSON data

Is it happening to me too, any solution?

**Comment by CodingAnonymous** [comment]
I have the error, too. Is there any solution yet?

**Comment by xdnan7** [comment]
I had the same problem too. Just logon to your dummy instagram account, go to menu Setting -> Login activity -> Confirm your login.

**Comment by davpirelli** [comment]
Still have the same problem but confirming location/captcha/sms doesn't work for me..still getting Unable to extract JSON data

**Comment by gergel0304** [comment]
Cleaning /cache folder help me
