### ISSUE TITLE
A Basic Question

### ISSUE THREAD

**Issue by lmoonwolf** [pgrimaud/instagram-user-feed#138]
I am trying to use this library. I made a mysql server via xampp, get it running, then created a php file and put the example code from readme. I run it with localhost and its running but it gives an error every time. e.g: (Symfony\Component\Cache\Adapter\FilesystemAdapter' not found).
 I dont acutally know how to use this library. Can anyone help?
Also i put the entire instagram-user-feed folder to the xampp main folder and created an example.php on instagram-user-feed/src

**Comment by pgrimaud** [comment]
Did you ran `composer install`?

**Comment by lmoonwolf** [comment]
no i didnt. where should i run composer install? in cmd?

**Comment by lmoonwolf** [comment]
i installed composer via regular installer for windows and its still gives an error

**Comment by lmoonwolf** [comment]
okay i managed to find how to do it.If anyone wondering; I opened node.js cmd and cd instagram-user-feed, then run composer install. Thanks for the asnwer anyway!

**Comment by lmoonwolf** [comment]
Sorry for spamming but its still not working. Gives the same error. the folder in the error is in vendor folder. Maybe its the problem?

**Comment by pgrimaud** [comment]
How did you install this projet on your folder ? 

Using a `composer require` or just cloning it?

**Comment by lmoonwolf** [comment]
i cloned it

**Comment by PrasadBroo** [comment]
i also had this issue i just placed ` require 'vendor/autoload.php'; ` on top of my code and it worked
