### ISSUE TITLE
Instagram error Checkpoint required, please provide IMAP credentials to process authentication.

### ISSUE THREAD

**Issue by jAKErCZ** [pgrimaud/instagram-user-feed#139]
Hello,
when setting up Instagram we popped out this error.

```
Instagram\Exception\InstagramAuthException

Checkpoint required, please provide IMAP credentials to process authentication.
```

May I ask how do I eliminate the error?

Thx

**Comment by pgrimaud** [comment]
Hello,

This error popped when email validation should be set using a code received by mail.
Did you try this one : https://github.com/pgrimaud/instagram-user-feed#version-63-checkpoint-challenge-bypass ?

**Comment by jAKErCZ** [comment]
> Hello,
> 
> This error popped when email validation should be set using a code received by mail.
> Did you try this one : https://github.com/pgrimaud/instagram-user-feed#version-63-checkpoint-challenge-bypass ?

Thx for help and I have the last query the **getMedias()** method returns all the media in the account but what if I only want to return the last 6?

**Comment by PrasadBroo** [comment]
@jAKErCZ  so this solution worked for you? im also facing same problem

**Comment by jAKErCZ** [comment]
> @jAKErCZ so this solution worked for you? im also facing same problem

Hi, I create new account to Instagram and no problem.

**Comment by PrasadBroo** [comment]
How many request you handel in a day from one account?

**Comment by jAKErCZ** [comment]
> How many request you handel in a day from one account?

currently about 5. Sometimes it wants to verify that the account is active, but after verification it runs again.

**Comment by camohub** [comment]
This is insane. Is there a link to IG support. This is not an API. This is corporate terror. I need images from owner site. I have login and password. Why should I parse an email..... I dont understand....

**Comment by pgrimaud** [comment]
> This is not an API.

Right, it's a scrapper.

**Comment by stuartcusackie** [comment]
By the way this also happens when Instagram detects suspicious activity, e.g. your server is located in a different country. Instagram now requires that you set a new password when this happens - Not sure how long it will work for after that.
