### ISSUE TITLE
Location is null on getMoreMedias results

### ISSUE THREAD

**Issue by stevelacey** [pgrimaud/instagram-user-feed#143]
**Version(s) affected**: 6.5.0

**Description**  
Location is `null` on every media result beyond the initial 12.

**How to reproduce**  
Call `getMoreMedias` and check the locations.

**Comment by pgrimaud** [comment]
Hello,
Sorry about the delay.

Unfortunately yes, I noticed that months ago. Location is always null after the initial 12 months. 😿

**Comment by stevelacey** [comment]
Yeah I appreciated the reason why that's the case after I looked through your code more, it's a shame. I ended up doing an extra media detail request per media to get the location, and that does at least get the job done.
