### ISSUE TITLE
Catch Error Handling

### ISSUE THREAD

**Issue by portmanager005** [pgrimaud/instagram-user-feed#144]
Hello,

maybe I want to search a Profile for an unexist user. I get this error:

Fatal error: Uncaught Instagram\Exception\InstagramFetchException: User nghdas96t42gasdassda not found in C:\xampp\htdocs\newinsta\vendor\pgrimaud\instagram-user-feed\src\Instagram\Transport\HtmlProfileDataFeed.php:34 Stack trace: #0 C:\xampp\htdocs\newinsta\vendor\pgrimaud\instagram-user-feed\src\Instagram\Api.php(124): Instagram\Transport\HtmlProfileDataFeed->fetchData('nghdas96t42gasd...') #1 C:\xampp\htdocs\newinsta\2.php(11): Instagram\Api->getProfile('nghdas96t42gasd...') #2 {main} thrown in C:\xampp\htdocs\newinsta\vendor\pgrimaud\instagram-user-feed\src\Instagram\Transport\HtmlProfileDataFeed.php on line 34

How I can handle this error to: 

"User not Found" ?

**Comment by pgrimaud** [comment]
You could catch error like this : 

```php
try {
    // init api blabla
    $profile = $api->getProfile('nghdas96t42gasdassda');

} catch (InstagramException $e) {
    print_r($e->getMessage());
}

```
