### ISSUE TITLE
How to use IMAP and get video link as mp4 on instagram?

### ISSUE THREAD

**Issue by clubmagic87** [pgrimaud/instagram-user-feed#145]
**Version(s) affected**: 6.5

**Description**  
1. I just updated to version 6.5 and reported an error with IMAP.
- Can someone tell good usage with this new function?
- Do I need to fill in my Gmail account? Does that account need to be related to my Instagram account?

2. How to get a video link as mp4 on Instagram?
- I can only get a thumbnail of the video. Don't know how to get a video link.
- I am using old version 6.2. Is it still usable? I'm seeing an issue in this version, even though it worked fine before. If possible can I use version 6.2 to get the video link?
`PHP Fatal error:  Uncaught Instagram\Exception\InstagramFetchException: Unable to extract JSON data in /vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php:53
Stack trace:
#0 /vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(104): Instagram\Transport\HtmlProfileDataFeed->fetchData('instagram')
#1 /process.php(560): Instagram\Api->getProfile('instagram')
#2 {main}
  thrown in /vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php on line 53
`

Sorry for asking these stupid questions but I'm really stuck.

**Comment by clubmagic87** [comment]
@pgrimaud can u help me?

**Comment by clubmagic87** [comment]
Solved itself.

**Comment by yan233dy** [comment]
Hi, how did you get a video link? Can you post some example? Thanks
