### ISSUE TITLE
Post Like

### ISSUE THREAD

**Issue by themayk** [pgrimaud/instagram-user-feed#146]
Thank you for your work, I have used some of its features and it works well, I want to ask if we can send likes ?, I examined but could not find it.

**Comment by pgrimaud** [comment]
Sorry for the delay, I was very busy.

I added a new feature "Like and unlike posts" on the last minor version [6.6](https://github.com/pgrimaud/instagram-user-feed/releases/tag/6.6.0).

You can now like post like [this](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/like.php) : 

```php
$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');

try {
    $api = new Api($cachePool);
    $api->login('login', 'password');

    // 2407752139969665290 is https://www.instagram.com/p/CFqDdCCFBkK/
    $postId = 2407752139969665290;

    $api->like($postId);

} catch (InstagramException $e) {
    print_r($e->getMessage());
} catch (CacheException $e) {
    print_r($e->getMessage());
}
```

Cheers
