### ISSUE TITLE
Getting Internal Errror Message [Instagram Rate Limit]

### ISSUE THREAD

**Issue by PrasadBroo** [pgrimaud/instagram-user-feed#148]
**Version(s) affected** 6.5.0

**Description**  
Im Getting  Uncaught Instagram\Exception\InstagramFetchException: Internal Error Message For Some Reason  When I Debugging I Found That Im Receiving Responce Status Code 429 Which Basically Means ` Too Many Requests ` .Anyone Facing Same Problem How You Bypassing Limit?Plz Help
**How to reproduce**  
Just Send More Than 200 requests withing hr and u will see above message.

**Comment by PrasadBroo** [comment]
@pgrimaud can you help me with this?

**Comment by pgrimaud** [comment]
Hello,

Sorry about the delay. I was very busy this last days.
Unfortunately, the rate limit is the limitation of this library.

To bypass it, you could use multiple accounts and adopt a strategy to rotate queries within accounts. For better performance, you could also use proxies.

**Comment by pgrimaud** [comment]
I was never facing this issue, cause I use this lib to retrieve small data from Instagram.

If you find a way to improve this limitation, I would glad to talk about it or feel free to open a PR. 😄

**Comment by PrasadBroo** [comment]
hi thnx for help i will try to find solution for this.
