### ISSUE TITLE
Get post location

### ISSUE THREAD

**Issue by purvik7373** [pgrimaud/instagram-user-feed#15]
Hi,

Is it possible to get post location?
Example: https://www.screencast.com/t/LYPw6Y4vNTJ

Thanks,

**Comment by pgrimaud** [comment]
Hi @purvik7373,

Unfortunately, post location data are not provided in user feed.
To retrieve post location, you can fetch and parse https://www.instagram.com/p/MEDIA_ID/?__a=1 for each media.

For example : https://www.instagram.com/p/BiefPWLBC2C/?__a=1.
`graphql > shortcode_media > location`

**Comment by purvik7373** [comment]
Hi @pgrimaud 

Sounds good! thanks for your reply.
