### ISSUE TITLE
Cache key "instagram.session.info@kaufmann.sk" contains reserved characters "{}()/@:".

### ISSUE THREAD

**Issue by camohub** [pgrimaud/instagram-user-feed#152]
**Version(s) affected**: 6.5

**Description**  
Symfony\Component\Cache\Exception\InvalidArgumentException
Cache key "instagram.session.info@kaufmann.sk" contains reserved characters "{}()/\@:".

**How to reproduce**  
```
	$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../../../storage/framework/cache');
	$api = new Api($cachePool);
	$api->login('info@kaufmann.sk', 'xxxxxxxx');
	$profile = $api->getProfile('kstlinfo');
	$media = $profile->getMedias();
```
**Additional context**  
I tried to use this library to show images from instagram but as it throws me and error 
Symfony\Component\Cache\Exception\InvalidArgumentException
Cache key "instagram.session.info@kaufmann.sk" contains reserved characters "{}()/\@:". 

What am I doing wrong? Thank you.

**Comment by PrasadBroo** [comment]
i guess you can only login only with username and password not with email and pass

**Comment by pgrimaud** [comment]
Fixed in [6.5.1](https://github.com/pgrimaud/instagram-user-feed/releases/tag/6.5.1).

**Comment by camohub** [comment]
I will test it tomorov. Thanks.

**Comment by camohub** [comment]
It works. Thanks a lot.
