### ISSUE TITLE
How to get hashtags from stories?

### ISSUE THREAD

**Issue by AntonioCS** [pgrimaud/instagram-user-feed#153]
**Version(s) affected**: 6.5

**Description**  
I can see a `getHashtags` method in `\Instagram\Model\Media` but why isn't there such a method in  `\Instagram\Model\StoryMedia`? Is this a limitation of instagram api or is it just missing from the library?

I would like to know if I'm going about this wrong and there is another way to get hashtags from stories.
Thanks

EDIT: Hashtags or Tags (the @things)

**Comment by pgrimaud** [comment]
Added in [6.5.1](https://github.com/pgrimaud/instagram-user-feed/releases/tag/6.5.1).

**Comment by pgrimaud** [comment]
Mentions retrieval is in [6.5.2](https://github.com/pgrimaud/instagram-user-feed/releases/tag/6.5.2). 👀
