### ISSUE TITLE
Uncaught TypeError: Return value of Instagram\Model\StoryMedia::getCtaUrl() 

### ISSUE THREAD

**Issue by AntonioCS** [pgrimaud/instagram-user-feed#154]
**Version(s) affected**: 6.5.0

**Description**  
Was testing some code:
```
       $feedStories = $api->getStories($profile->getId());
       $stories = $feedStories->getStories();

       foreach ($stories as $story) {
           echo "Ctaurl: " , $story->getCtaUrl() , "\n";
       }
```` 
and got;
```
Ctaurl: PHP Fatal error:  Uncaught TypeError: Return value of Instagram\Model\StoryMedia::getCtaUrl() must be of the type string, null returned in /application/vendor/pgrimaud/instagram-user-feed/src/Instagram/Model/StoryMedia.php:250
```
**How to reproduce**  
Grab data from instagram that doesn't have this.

**Possible Solution**  
Use `?string` instead of just `string`, and I would recommend to use `?<datatype>` on all `get` functions.

**Comment by pgrimaud** [comment]
Thanks, fixed in [6.5.1](https://github.com/pgrimaud/instagram-user-feed/releases/tag/6.5.1). 😄
