### ISSUE TITLE
Is it possible to get next medias via ajax call as separate request?

### ISSUE THREAD

**Issue by camohub** [pgrimaud/instagram-user-feed#157]
**Version(s) affected**: 6

**Description**  
Is it possible to get more medias via ajax call. It means if I load first 10 images and then wants to get next 10 images but as a separate request. Is there a way to start on the position stored in some kind of cache?

**Additional context**  
I would like to fill carousel which should load more images dynamically. 

Is it possible or not?

**Comment by pgrimaud** [comment]
Hello,

Yes it's possible. You can use the `getMoreMediasWithCursor`method in Api.php. 

Example : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/medias-endcursor.php

**Comment by camohub** [comment]
Thanks a lot. I solved it in another way. Now I am facing InstagramAuthException(code: 0): Checkpoint required, please provide IMAP credentials to process authentication. issue. Hope this doc help me to solve it https://github.com/pgrimaud/instagram-user-feed#version-63-checkpoint-challenge-bypass
