### ISSUE TITLE
Get story Geo Location tags

### ISSUE THREAD

**Issue by AntonioCS** [pgrimaud/instagram-user-feed#158]
Hey,

On the newest version (6.5.2) you've added the ability to retrieve mentions and hashtags from stories which is great, but I think you can also retrieve something else called Geo Location Tags. 

So for example in this screenshot of this video in a user story:

![image](https://user-images.githubusercontent.com/1086401/98364170-3a127180-2028-11eb-937d-b019308b7ea0.png)

The geo location tags would be `little choc apothecary`.
Would it be possible to add this in the next version?
Many thanks!

**Comment by pgrimaud** [comment]
ref to https://github.com/pgrimaud/instagram-user-feed/commit/a4f2e8e3ac97cdbd07c9b2d347ddc03d670fd6a0, released in [6.6.2](https://github.com/pgrimaud/instagram-user-feed/releases/tag/6.6.2)

😄
