### ISSUE TITLE
IMAP php extension must be enabled to bypass checkpoint_challenge.

### ISSUE THREAD

**Issue by xbfast** [pgrimaud/instagram-user-feed#160]
Hello good I am trying to use your code. If I do it in the normal way, it asks for the SMTP. I have tried checkpoint-challenge.php but it returns this error: IMAP php extension must be enabled to bypass checkpoint_challenge

**Comment by pgrimaud** [comment]
You should install PHP IMAP extension to use it.

Depending of your PHP version, something like that : https://riptutorial.com/php/example/24417/install-imap-extension

For docker, you could check here : https://github.com/pgrimaud/instagram-user-feed/blob/master/ci/php74/Dockerfile

Best

**Comment by xbfast** [comment]
Could you put an option on how to use it in laravel? how the controller is configured to output the information in a view @pgrimaud

**Comment by xbfast** [comment]
I'm trying to install on a Ubuntu 18.04, but the following happens to me `sudo apt-get install php7.0-imap`

```
Reading package list ... Done
Creating dependency tree
Reading the status information ... Done
E: The php7.0-imap package could not be located
E: Could not find any packages using "*" with "php7.0-imap"
E: Could not find any package with regular expression "php7.0-imap"
```

**Comment by pgrimaud** [comment]
You should install IMAP ext for your PHP version.
If you are running PHP 7.3, just run `apt-get install php7.3-imap`.

> Could you put an option on how to use it in laravel? how the controller is configured to output the information in a view @pgrimaud

It's a simple PHP library, you could use all examples directly into your controller method, then pass result to your view.

```php
// ... api call and stuff
$profile = $api->getProfile('robertdowneyjr');

return view('instagram.index', compact('profile'));
```

**Comment by xbfast** [comment]
okay! and once imap php is installed, where do I put the code of the checkpoint that you use?
