### ISSUE TITLE
400 Bad Request while checkpoint challenge

### ISSUE THREAD

**Issue by bytehead** [pgrimaud/instagram-user-feed#163]
**Version(s) affected**: 6.6.2

**Description**  
During login, after submitting the checkpoint challenge, a 400 bad request is the result.

**How to reproduce**  
Try to login where you have to verifiy your account with a challenge delivered by mail.

**Possible Solution**  
~~n/a - still investigating. Is it possible that instagram somehow changed the API? Does anybody know?~~
Add a longer delay to wait for emails droppin' into the mailbox.

**Additional context**  
Error message:
```
In RequestException.php line 113:
                                                                                                                                           
  [GuzzleHttp\Exception\ClientException (400)]                                                                                             
  Client error: `POST https://www.instagram.com/challenge/1476511775/A6giahcBX6/` resulted in a `400 Bad Request` response:                
  {"message": "", "challenge": {"challengeType": "VerifyEmailCodeForm", "errors": ["Please check the code we sent you and  (truncated...)  
```

**Comment by bytehead** [comment]
I've an assumption - mail delivery takes to long. it reads an old verification mail 🙈

**Comment by bytehead** [comment]
Just tested #164 on production with a delay of 30secs and it works 🙃

**Comment by pgrimaud** [comment]
Thank you!
