### ISSUE TITLE
Your Account Has Been Temporarily Locked

### ISSUE THREAD

**Issue by amro80** [pgrimaud/instagram-user-feed#165]
**Version(s) affected**: x.y.z

**Description**  
There is a page before the challenge email page that says "Your Account Has Been Temporarily Locked"
I think the script need to send a response for it with the continue button, this will proceed to the email send code page.

**How to reproduce**  
need to use a temp blocked account
**Possible Solution**  
I think, need to add action to press the continue button.

**Comment by amro80** [comment]
any news?

**Comment by l-uke** [comment]
This just happened to about 40+ plus of my Instagram accounts. 
They had an average of 400 requests in 24 hrs. They each had their own proxy IP. 
Was it too many requests ?
if so then how many requests can I do ?

**Comment by amro80** [comment]
yes about 1400 req in 24 hrs for the 4 accounts. IG disabled all of them.

Now I am using 10 accounts!

**Comment by amro80** [comment]
I found that the response code is 200 with displayed message "syntax error". I checked the response from IG and found it is requesting phone verification with SMS.  
what do you suggest?

**Comment by recoverjp** [comment]
> I found that the response code is 200 with displayed message "syntax error". I checked the response from IG and found it is requesting phone verification with SMS.
> what do you suggest?

I have the same problem. And instagram only accepts two accounts per cell phone number.

**Comment by samuelhgf** [comment]
Any news about this?

**Comment by recoverjp** [comment]
> Any news about this?

Infelizmente não, Samuel.
Ainda não consegui descobrir o problema.
Já pesquisei muito, mas ninguém fala sobre a solução pra isso.
Se você conseguir algum avanço, por favor me fala.
