### ISSUE TITLE
Error with Checkpoint challenge

### ISSUE THREAD

**Issue by A-0-0-P** [pgrimaud/instagram-user-feed#170]
**Version(s) affected**: 6.6.4

**Description**  
I can't log into Instagram without the 'Checkpoint challenge bypass'.

So I tried to implement this example: checkpoint-challenge.php
But I just get this error. 
Is it something on my side, or some change that Instagram made and breaks the code?
Thanks for any input ! 

`Fatal error: Uncaught TypeError: Argument 4 passed to Instagram\Auth\Checkpoint\Challenge::__construct() must be of the type int, null given, called in /Users/Me/Sites/localhost/_instagram_feed4/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php on line 134 and defined in /Users/Me/Sites/localhost/_instagram_feed4/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Checkpoint/Challenge.php:45 Stack trace: #0 /Users/Me/Sites/localhost/_instagram_feed4/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php(134): Instagram\Auth\Checkpoint\Challenge->__construct(Object(GuzzleHttp\Client), Object(GuzzleHttp\Cookie\CookieJar), '/challenge/1015...', NULL) #1 /Users/Me/Sites/localhost/_instagram_feed4/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php(101): Instagram\Auth\Login->checkpointChallenge(Object(GuzzleHttp\Cookie\CookieJar), Object(stdClass)) #2 /Users/Me/Sites/localhost/_instagram_feed4/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(108): Instagram\Auth\Login->process in /Users/Me/Sites/localhost/_instagram_feed4/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Checkpoint/Challenge.php on line 45`

**Comment by AntonioCS** [comment]
It's probably some issue with the account.
I had this issue when I deployed my script on aws and Instagram flagged the account because it was being used from the US instead of from the UK.

**Comment by recoverjp** [comment]
> It's probably some issue with the account.
> I had this issue when I deployed my script on aws and Instagram flagged the account because it was being used from the US instead of from the UK.

And did you find a solution for that?

**Comment by AntonioCS** [comment]
@recoverjp the account holder has to login and follow instagram instructions to rectify the account

**Comment by recoverjp** [comment]
I did not understand. The best solution would be to create an account in the USA if I am going to use AWS?

**Comment by recoverjp** [comment]
![image](https://user-images.githubusercontent.com/5755850/101560870-ff8f5200-39a2-11eb-8b6b-2b0042b61248.png)
The problem is here, as $ this->challengeDelay is being sent as null. And even if we have an integer value, then there is an error in the sendSecurityCode function because there is no such key 0 and these values.
![image](https://user-images.githubusercontent.com/5755850/101560989-3c5b4900-39a3-11eb-809a-fd799c1d168a.png)
Anyway, I haven't figured out how to solve it.
