### ISSUE TITLE
SPAN? {"message": "", "spam": true, "status": "fail"}

### ISSUE THREAD

**Issue by rafanake** [pgrimaud/instagram-user-feed#173]
**Version(s) affected**: 6.6.4

**Description**  
Hey guys, have anyone faced this issue?  I've been fetching data  every 2.5 minutes, Have no idea they are going to flag it as SPAN. There's a way to avoid it? How many requests do you guys are sending by day?
This Library is fantastic but Instagram really SUCKS! Damn.

**Additional context**  
object(Instagram\Exception\InstagramAuthException)#38 (7) {
  ["message":protected]=>
  string(201) "Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response:
{"message": "", "spam": true, "status": "fail"}

**Comment by mnajafzadeh** [comment]
Same issue here. Works well on my localhost but {"message": "", "spam": true, "status": "fail"} error on the live server.
