### ISSUE TITLE
Your Account Has Been Temporarily Locked

### ISSUE THREAD

**Issue by samuelhgf** [pgrimaud/instagram-user-feed#179]
#165

**Comment by pgrimaud** [comment]
Hello @samuelhgf 

Sorry for the delay. Do you share an account with temp blocked account ? Because I can't reproduce it.

You can DM me : https://twitter.com/pgrimaud_

Thanks

**Comment by LeBenLeBen** [comment]
I have the same issue, after a bunch of days the account used to fetch data is flagged as suspicious. First time you have to add a phone number and confirm it and it works again for a while. After a week or two, it gets blocked again and this time you have to change the password as it thinks it has been used by one of those "fake instagram websites".

I thought the plugin was fetching and caching the results to not do too many requests, but actually all it caches is the session token, right? So I should implement caching of the data on my own, is that correct?
