### ISSUE TITLE
Instagram\Exception\InstagramAuthException Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response: {"message": "", "spam": true, "status": "fail"}

### ISSUE THREAD

**Issue by rahul7yadav** [pgrimaud/instagram-user-feed#180]
Hi @pgrimaud , I used your instagram feed code and it's working on my localhost and I uploaded my code on server and after 12 hours it's suddenly stop working and showing error like:
`Instagram\Exception\InstagramAuthException
Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response: {"message": "", "spam": true, "status": "fail"}
`
Please take look and let me know how to fix it .

Thanks!!

**Comment by volkv** [comment]
I can confirm such behavior. Probably caused by Instagram protocol updates

**Comment by ollea** [comment]
Tried with 3 different accounts and got the same issue

**Comment by rahul7yadav** [comment]
I think Instagram block my server IP for next 24 hours after this error gone automatically .

**Comment by pgrimaud** [comment]
Hello @rahul7yadav, @volkv, @ollea 

Sorry for the delay. Do you share an account with temp blocked account ? Because I can't reproduce it.

You can DM me : https://twitter.com/pgrimaud_

Thanks

**Comment by ollea** [comment]
Hello, thanks for your response.
It's now solved, actually the hosting server was considered as spam by Instagram as they received too much queries and were returning HTTP 429 - too many requests.
We had to wait a few days before they reconsider the hosting server as ham again.

**Comment by ollea** [comment]
Actually the problem came back:
```
Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response:
{"message":"","spam":true,"status":"fail"}
```
This website is on a shared server, so other clients use the same IP to get different Instagram accounts medias, have you any idea to solve this?
Thanks in advance

**Comment by brimacbain** [comment]
Also having the same issue- I've implemented caching, grabbing new items from the feed every 60 minutes only.  Set it up on a new server to test out, and I don't think it even logged in once (checked the Instagram account login history and server didn't show up there)- it looks like it just instantly detects it as spam even on a new IP address that's never made a request to the server yet.

**Comment by afsh7n** [comment]
Hello. Is there a solution to this problem? Is there a script that can change the IP?

**Comment by dwainscheeren** [comment]
Got the same issue here on a fresh DO server.

**Comment by fiction13** [comment]
Also having the same issue.

**Comment by kautiontape** [comment]
It definitely seems linked to Instagram blocking whole sections of known servers, likely entire IP blocks. A fresh run on my local computer loads fine, but the first run on Digital Ocean results in a permanent 429. It seems like the way around it is to proxy through an IP not included in a prohibited list, like how restyler/instagram-php-scraper uses RapidAPI.

**Comment by ranaharoon** [comment]
I got the same problem, The most preferably script seems to be working locally just. This is tested if you send few requests fastly like pagination using endCursor then your ISP IP gets banned or restricted, restarting router works again. I've tested with 3 different Hosting accounts, once i uploaded to shared server it showed problem because instagram considered it a suspicious login attempt which requires security code on mobile or email. then i used another instagram login account for live after login into my browser then executed script on shared hosting. it worked only for few requests. This time it was 429. So my all 3 different hosting IPs got restricted while i used sleep(2) before any endCursor requests. There should be a proper solution for it.

**Comment by karrarjasim** [comment]
Same problem here!

**Comment by dwainscheeren** [comment]
Please re-open still not fixed.

**Comment by livevasiliy** [comment]
Have same error launch on Heroku server, on localhost, not errors.

**Comment by volkv** [comment]
Instagram is blocking bot-suspicious IPs from login. Any ideas how to bypass this?

**Comment by andressavw** [comment]
Also having the same issue.

**Comment by harshshah8996** [comment]
Also facing same issue. Is there any update or how to fix it?
