### ISSUE TITLE
Hashtag feed

### ISSUE THREAD

**Issue by davimatos** [pgrimaud/instagram-user-feed#185]
Hi!

First of all, thank you for keeping this project very useful for the community.

I needed to get the list of photos from a hashtag, like the contents of that URL: https://www.instagram.com/explore/tags/brazil/

Would it be possible to implement this feature?

**Comment by pgrimaud** [comment]
Hello @davimatos 

I released v6.7.0 which contains the way to fetch pictures from an hashtag.

You could find an example here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/hashtag.php

**Comment by davimatos** [comment]
Perfect! Thanks!
