### ISSUE TITLE
sidecar images

### ISSUE THREAD

**Issue by henzan02** [pgrimaud/instagram-user-feed#19]
Hello,
could you please add sidecar image in DisplaySrc? thanks

**Comment by pgrimaud** [comment]
@henzan02 Sidecar image?

**Comment by henzan02** [comment]
Yep.. I mean Carousel Images. 

Like this https://www.instagram.com/p/BiTCVAqD5bp/?taken-by=instagram

**Comment by pgrimaud** [comment]
Unfortunately, carousel images data are not provided in user feed.
To retrieve carousel images, you can fetch and parse https://www.instagram.com/p/MEDIA_ID/?__a=1 for each **GraphSidecar** media.

e.g. https://www.instagram.com/p/BjUMpQwnSV-/?__a=1
`graphql > shortcode_media > edge_sidecar_to_children `

**Comment by henzan02** [comment]
Okay @pgrimaud  I will try. 

Thanks
