### ISSUE TITLE
Error Report: 403 Forbidden

### ISSUE THREAD

**Issue by mrkatz** [pgrimaud/instagram-user-feed#191]
Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `403 Forbidden` response: {"message":"Please wait a few minutes before you try again.","status":"fail"}

This was after I was receiving the error msg: "'Wrong login / password'"

The correct username/password was being used.

**Comment by jeremymouton** [comment]
I've seen this Instagram error when connected to a VPN.
