### ISSUE TITLE
When challenge code contains first 0 simbol verification is broken

### ISSUE THREAD

**Issue by Kachit** [pgrimaud/instagram-user-feed#195]
**Version(s) affected**: 6.7.0

**Description**  
When challenge code contains first **0** simbol verification is broken because 'security_code' => (int)$code,

**How to reproduce**  
When code is 081675 library send parameter security_code=81675

**Possible Solution**  
`
public function submitSecurityCode(\StdClass $challengeContent, string $code): CookieJar
    {
        // here we create a new CookieJar to retrieve real session cookies
        $cookieJarClean = new CookieJar();

        $cookie      = 'ig_cb=1; ig_did=' . $challengeContent->device_id . '; csrftoken=' . $challengeContent->config->csrf_token . '; mid=' . $this->getMidCookie();
        $postHeaders = [
            'form_params' => [
                'security_code' => $code,
            ],
            'headers'     => [
                'x-instagram-ajax' => $challengeContent->rollout_hash,
                'content-type'     => 'application/x-www-form-urlencoded',
                'accept'           => '*/*',
                'user-agent'       => UserAgentHelper::AGENT_DEFAULT,
                'x-requested-with' => 'XMLHttpRequest',
                'x-csrftoken'      => $challengeContent->config->csrf_token,
                'x-ig-app-id'      => 123456889,
                'referer'          => $this->checkPointUrl,
                'cookie'           => $cookie,
            ],
            'cookies'     => $cookieJarClean
        ];

        $res3 = $this->client->request('POST', $this->checkPointUrl, $postHeaders);

        $codeSubmissionData = json_decode((string)$res3->getBody());

        if ($codeSubmissionData->status === 'ok') {
            return $cookieJarClean;
        } else {
            throw new InstagramAuthException('Unknown error, please report it with a GitHub issue.');
        }
    }
`

**Comment by pgrimaud** [comment]
Nice catch @Kachit 

It should be fixed on [6.7.2](https://github.com/pgrimaud/instagram-user-feed/releases/tag/6.7.2).
