### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by monsterJKB** [pgrimaud/instagram-user-feed#198]
**Version(s) affected**: x.y.z
hi  how to use the proxy?
**Description**  
A clear and concise description of your problem.

**How to reproduce**  
Code and/or config needed to reproduce your problem.

**Additional context**  
Optional: any other context about the problem: log messages, screenshots, etc.

**Comment by pgrimaud** [comment]
Hello, you can find an example [here](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/using-proxies.php)

**Comment by monsterJKB** [comment]
cURL error 7: Failed to connect to www.instagram.com port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by monsterJKB** [comment]
wrong password? IP for Instagram requests : 158.247.199.76 Your IP : 113.250.252.10 Wrong login / password
