### ISSUE TITLE
Laravel avoid multiple login

### ISSUE THREAD

**Issue by aminejafur** [pgrimaud/instagram-user-feed#206]
Hello,
First thanks for the effort in this package,

I am building a small app using Laravel and to achieve some goals i will need to login to my instagram account before getting data from instagram, but i want to avoid multiple login over each request to these functionalities, what is the best solution to do this?
For now i am going to use a singleton Class which will get an instance from the logged Class, any other suggestions are more than welcome!

Thanks in advance.

**Comment by pgrimaud** [comment]
Hello, 

It depends how your login process is working?
Are you using Jetstream or a custom one you made?

You may also try to achieve it with a service provider.
