### ISSUE TITLE
Video url on toArray()

### ISSUE THREAD

**Issue by nam-co** [pgrimaud/instagram-user-feed#211]
Hi, thanks for the work on the package, I just starting and trying to get the video file url (normally a mp4 file) but I don't see the link in the toArray() function, is it possible to get this url? just to see Im doing anything wrong here is my code:
```
        $profile = $api->getProfile('robertdowneyjr');
        $medias1 = $profile->toArray();
        sleep(1);
        $medias2= $api->getMoreMedias($profile)->toArray();
        $medias = array_merge($medias1['medias'],$medias2['medias']);
```

Appreciate any help, thanks

**Comment by nam-co** [comment]
Thanks @pgrimaud seems like a logical feature

**Comment by pgrimaud** [comment]
@nispeon Could you take a look at this enhancement please? 😄

**Comment by pgrimaud** [comment]
@nam-co We add `getVideoUrl` method in `Media` model. You could try in 6.8.0.

Best

**Comment by nam-co** [comment]
Thanks @pgrimaud have a good day
