### ISSUE TITLE
Not showing my account

### ISSUE THREAD

**Issue by krishhhnaaaaaaa** [pgrimaud/instagram-user-feed#213]
**Version(s) affected**: x.y.z

**Description**  
A clear and concise description of the problem.

**How to reproduce**  
Code and/or config needed to reproduce the problem.

**Possible Solution**  
Optional: only if you have suggestions on a fix/reason for the bug

**Additional context**  
Optional: any other context about the problem: log messages, screenshots, etc.

**Comment by pgrimaud** [comment]
What's the problem?
