### ISSUE TITLE
Issues on getFeed() with setEndCursor()

### ISSUE THREAD

**Issue by artursantos-fba** [pgrimaud/instagram-user-feed#22]
Does anyone is getting errors on retrieving the 2nd page of medias (>12)?
I had this working just fine but looks like IG did some changes again.
Not sure how to workaround this.
Thanks

**Comment by amacrae** [comment]
I know this is a closed issue, but I am also having this problem. Did anyone find a solution?

**Comment by pgrimaud** [comment]
Hello @amacrae,

I executed the file `example/medias.php` and it works like a charm. Did you try with your account?

**Comment by amacrae** [comment]
Hi @pgrimaud 

I'm using v5.0 because it's for a client's feed. I could of course ask for their login credentials to obtain an access token, but I'd rather see if I can do without it.

If I add an extra third page to `example/medias.php` it will get the first 24 media items and then return a fatal error (ie when it tries for the third page):

```
// (existing code in example)

// Third Page
    $api->setEndCursor($feed->getEndCursor());
    sleep(1); 
    $feed = $api->getFeed();
    echo "\n\n";
    echo '============================' . "\n";
    echo 'Medias third page : ' . "\n";
    echo '============================' . "\n\n";
    /** @var \Instagram\Hydrator\Component\Media $media */
    foreach ($feed->getMedias() as $media) {
        echo 'ID        : ' . $media->getId() . "\n";
        echo 'Caption   : ' . $media->getCaption() . "\n";
        echo 'Link      : ' . $media->getLink() . "\n";
        echo 'Likes     : ' . $media->getLikes() . "\n";
        echo 'Date      : ' . $media->getDate()->format('Y-m-d h:i:s') . "\n";
        echo '============================' . "\n";
    }
```

```

Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 56: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\www\covrd\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186
Stack trace:
#0 C:\xampp\htdocs\www\covrd\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\xampp\htdocs\www\covrd\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\xampp\htdocs\www\covrd\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 C:\xampp\htdocs\www\covrd\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): Gu in C:\xampp\htdocs\www\covrd\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186```

**Comment by pgrimaud** [comment]
That's weird. I tried with my Instagram account and I could retrieve the first four pages without any error.

But I tested it on Linux OS, and it seems you're running the script on Windows OS.
That's the only difference I can see here. What's the Instagram account you wanna retrieve?

**Comment by amacrae** [comment]
Ok! Now we're cooking with gas! I tried it on my Linux machine and it works as it should. 

My guess is that the issue lies with my network configuration and/or cURL + OpenSSL - all of which are a bit beyond me. I now wonder if the OP had my exact problem or whether the issue is specific to me. 

I'd love to get it running on my Windows machine, but I can definitely build in a workaround. Any thoughts? Happy to mark as closed :)

**Comment by pgrimaud** [comment]
SSL_ERROR_SYSCALL is, in your case, linked to your xampp server configuration. But I have no idea how to fix it. 

Maybe that's why I never develop on Windows environment. 🙄

**Comment by pgrimaud** [comment]
Hmm I have no idea how to fix it...

It works for me on 4 different servers (2xDebian, 1xCentOS, 1xUbuntu). Did you try on other IP or ISP?
