### ISSUE TITLE
resulted in a `429 -` response: {"message":"","spam":true,"status":"fail"}

### ISSUE THREAD

**Issue by azerioid** [pgrimaud/instagram-user-feed#222]
**Version(s) affected**: x.y.z

**Description**  

 Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response:
{"message":"","spam":true,"status":"fail"}
**How to reproduce**  
$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');

$api = new Api($cachePool);
$api->login('', ''); // mandatory
$profile = $api->getProfile('inna');

**Comment by YannBoyongo** [comment]
i got similar error too 

`Internal error: Client error: `GET https://www.instagram.com/florandia.be/` resulted in a `429 -` response`
