### ISSUE TITLE
Argument 1 passed to Instagram\Api::__construct() must be an instance of Psr\Cache\CacheItemPoolInterface, instance of Symfony\Component\Cache\Adapter\FilesystemAdapter given

### ISSUE THREAD

**Issue by haigooner95** [pgrimaud/instagram-user-feed#224]
T got this error, can you help me @pgrimaud ?

**Comment by pgrimaud** [comment]
What is your code ?

**Comment by haigooner95** [comment]
$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');
        $this->login_session = new Api($cachePool);

**Comment by haigooner95** [comment]
i followed your usage

**Comment by pgrimaud** [comment]
Did you require the good namespace?


use Symfony\Component\Cache\Adapter\FilesystemAdapter;

**Comment by haigooner95** [comment]
> Did you require the good namespace?
> 
> use Symfony\Component\Cache\Adapter\FilesystemAdapter;

yes, i did.

**Comment by pgrimaud** [comment]
Could you paste the entire file where you're using this package?

Are you using 6.x version?

Are you in Symfony environment or other framework?

**Comment by haigooner95** [comment]
I'm using Laravel 7, and 6x version of this package. I'm using this in a queue job

**Comment by pgrimaud** [comment]
Which version of `symfony/cache` are you using?
