### ISSUE TITLE
Only the first 12 media have accessibility caption

### ISSUE THREAD

**Issue by pattihis** [pgrimaud/instagram-user-feed#225]
**Version(s) affected**: 6.8

**Description**  
`$media->getAccessibilityCaption()` is always empty for every media after the `$api->getMoreMedias($profile)` is called. 

**How to reproduce**  
Only the first 12 Medias have values for their `getAccessibilityCaption()`. All other media from there on have empty accessibility captions.

**Additional context**  
Tested with many Instagram accounts.

**Comment by pgrimaud** [comment]
Hello,

Sorry, I totally missed your message. 😞 

Ref to https://github.com/pgrimaud/instagram-user-feed/issues/83#issuecomment-647615360, accessibility caption are only available on the first 12 medias.

I just made a new check and can't find a way to fetch it, sorry.

**Comment by nestl1ng** [comment]
I have the same problem, as I understand it is impossible to get more than 12 posts using your library?

**Comment by nestl1ng** [comment]
Hi @pattihis Have you solved this problem?
