### ISSUE TITLE
Return username in Media object

### ISSUE THREAD

**Issue by davimatos** [pgrimaud/instagram-user-feed#230]
Hi!

I'm having a problem using the library, more specifically when I need to retrieve media by hashtag.

Since hashtag media are returned from multiple users, you would need to get at least the username of the media owner. This way, I would be able to get the profile information using the other methods.

If there is an alternative way to get this information, it would help a lot.

Thanks

**Comment by pgrimaud** [comment]
Now you could retrieve the userId from media. Unfortunately not the username, but you could query to fetch username using the `getProfileById` method. Available in >=6.9

**Comment by davimatos** [comment]
Great! Thanks a lot

**Comment by davimatos** [comment]
Great! Thanks a lot!
