### ISSUE TITLE
Feed slides are possible !

### ISSUE THREAD

**Issue by RoseGoli** [pgrimaud/instagram-user-feed#231]
Hi
First of all tnx for your amazing library !
I just find this useful lib and start to work with it

But found out that this lib cant fetch mutiple slides of a post
So i saw py libs that did this befor and find a way 😃 

You should add a `&__b=1` at the end of [This Url](https://github.com/pgrimaud/instagram-user-feed/blob/1bfeba4ffa8bb2a9bf27584263f3a1dd30dcb635/src/Instagram/Transport/JsonMediaDetailedDataFeed.php#L21)  !

Then in the json result you can find multiple `display_resources` index that contains multiple urls of slides with multiple width & height 💯 

I hope you could add this feature soon 🤍

**Comment by pgrimaud** [comment]
Hello,

You can already fetch all medias of post using the actual code.

If you check the example here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/media-detailed.php which fetch pictures from : https://www.instagram.com/p/CAnqPB-Jzcj/

You could find the 3 pictures by using the `$mediaDetailed->getSideCarItems()` method.
