### ISSUE TITLE
Unable to extract JSON data

### ISSUE THREAD

**Issue by nortonkh71** [pgrimaud/instagram-user-feed#232]
hello 
My site was working properly right but tonight suddenly encountered this eccentric:

Unable to extract JSON data/home/.../vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php#53Instagram\Exception\InstagramFetchException
`preg_match('/<script type="text\/javascript">window\.__additionalDataLoaded\([^,]*,(.+)\);<\/script>/', $html, $matches);          if (!isset($matches[1])) {             throw new InstagramFetchException('Unable to extract JSON data');         }          $data = json_decode($matches[1], false);`

**Comment by stevelacey** [comment]
+1

**Comment by pgrimaud** [comment]
Is it resolved?

If not, could you give me more informations about the account you try to fetch? Thanks!

**Comment by nortonkh71** [comment]
No
thanks for reply
this is my site
https://test.applex.ir/

laravel debuger is anable
please enter a instagram page in field and click on "جستجو"

Error details are displayed

I think it is blocked by Instagram 

thnak you

**Comment by pgrimaud** [comment]
Could you send me the content of`$html` here (https://github.com/pgrimaud/instagram-user-feed/blob/master/src/Instagram/Transport/HtmlProfileDataFeed.php#L43) by email : grimaud.pierre@gmail.com

Thanks

**Comment by gergel0304** [comment]
Cleaning /cache folder help me
