### ISSUE TITLE
Multiple Account Get Follow By User

### ISSUE THREAD

**Issue by neetkiss** [pgrimaud/instagram-user-feed#233]
How do I manage to send followers with multiple accounts?
Code I used;

`$credentials = DB::table('takipcis')->get();
        $cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');
        foreach($credentials as $credential):
            try {
                $api = new Api($cachePool);
                $api->login($credential->username, $credential->password);
                // 1518284433 is robertdowneyjr's account id
                $getUserID = $api->getProfile($request->post('followerUrl'));
                $userId = $getUserID->id;

                $follow = $api->follow($userId);
            
                //echo $follow . PHP_EOL;
            
            } catch (InstagramException $e) {
                print_r($e->getMessage());
            } catch (CacheException $e) {
                print_r($e->getMessage());
            }
            sleep(1);
        endforeach;`

**Comment by pgrimaud** [comment]
I'm not sure what you really want?

Could you explain more?
