### ISSUE TITLE
How to download other url reels, images etc.

### ISSUE THREAD

**Issue by Rk-choudhary-ck** [pgrimaud/instagram-user-feed#235]
Hii 
i just want to download all types of videos like reels, tv etc url with the help of this library ..  how it possible. ??

**Comment by pgrimaud** [comment]
Not yet, but I'm working on an update to fetch Reels & IGTV actually.

**Comment by pgrimaud** [comment]
I just released the [6.10](https://github.com/pgrimaud/instagram-user-feed/releases/tag/6.10.0) version where you can try to retrieve Reels & IGTV.

Feedback appreciated.
