### ISSUE TITLE
MediaDetailed getDisplaySrc return null Value wheeras typing is string 

### ISSUE THREAD

**Issue by n-richaud** [pgrimaud/instagram-user-feed#236]
**Version(s) affected**: 6.8.0

**Description**  
When trying to fetch nikefootball instgram (id : 23678829 ) 
the media of type GraphVideo with id : 2653393490909939243 and shortcode CTSv1JbBUYr , trigger a warning because the displaySrc field is empty whereas the typeHint make it mandatory.
The Media is part of a sideCar Post 

**How to reproduce**  
Fetch Media with this link 'https://www.instagram.com/p/CTSv3j1hGIh/' using
getMediaDetailed
**Possible Solution**  
Made the field displaySrc nullable

**Additional context**  
Instagram\Model\Media::getDisplaySrc(): Return value must be of type string, null returned

**Comment by pgrimaud** [comment]
Hello,

Thanks for the issue. I just fixed it on v6.9.0
