### ISSUE TITLE
two factor

### ISSUE THREAD

**Issue by Bazzastyle** [pgrimaud/instagram-user-feed#237]
**Version(s) affected**: 6.10.0

**Additional context**  

> PHP Fatal error:  Uncaught Instagram\Exception\InstagramAuthException: Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `400 Bad Request` response:
> {"message":"","two_factor_required":true,"two_factor_info":{"pk":...,"username":"...","sms_two_fact (truncated...)
>  in /var/www/bot/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php:104
> Stack trace:
> #0 /var/www/bot/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(121): Instagram\Auth\Login->process()
> #1 /var/www/bot/ProjectOneXBot/ig_user.php(10): Instagram\Api->login()
> #2 {main}
>   thrown in /var/www/bot/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php on line 104

**Comment by pgrimaud** [comment]
It seems you have a 2FA on this account. 
Email or SMS ?

**Comment by lucasdelavrapinto** [comment]
> It seems you have a 2FA on this account.
> Email or SMS ?

I had the same problem, Its SMS for me.
