### ISSUE TITLE
[Your requirements could not be resolved to an installable set of packages.]

### ISSUE THREAD

**Issue by himanshuaiza** [pgrimaud/instagram-user-feed#238]
PHP version -- PHP 7.4.3 (cli) (built: Aug 13 2021 05:39:12) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

running on wsl2 ubuntu

 Problem 1
    - Installation request for pgrimaud/instagram-user-feed ^6.10 -> satisfiable by pgrimaud/instagram-user-feed[6.10.0].
    - pgrimaud/instagram-user-feed 6.10.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/15-xml.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-dom.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-simplexml.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.4/cli/conf.d/20-xsl.ini
    - /etc/php/7.4/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
Installation failed, deleting ./composer.json.

**Comment by pgrimaud** [comment]
You have to enable curl extension.

Maybe try:

- apt-get update
- apt-get install php7.4-curl

**Comment by himanshuaiza** [comment]
Thank you very much , It worked.

**Comment by pgrimaud** [comment]
Cool! Feel free to open another issue if you have any other issue 😄

**Comment by himanshuvv** [comment]
Hello, this is the issue.
LINE 11 - require realpath(dirname(__FILE__)) . '/../vendor/autoload.php';
{Media & Story highlight example}
PHP Warning:  require(/home/himanshu/../vendor/autoload.php): failed to open stream: No such file or directory in /home/himanshu/smsa.php on line 11
PHP Fatal error:  require(): Failed opening required '/home/himanshu/../vendor/autoload.php' (incl_path='.:ude/usr/share/php') in /home/himanshu/smsa.php on line 11

**Comment by pgrimaud** [comment]
It's a require file error. Are you sure about your autoload.php path?

**Comment by himanshuvv** [comment]
Yes it worked, the path was the issue.
