### ISSUE TITLE
Get tagged media

### ISSUE THREAD

**Issue by dejvidecz** [pgrimaud/instagram-user-feed#239]
Is there any way to get all Tagged photos?

for example https://www.instagram.com/robertdowneyjr/tagged/

Thanks for help :)

**Comment by pgrimaud** [comment]
Hello,

I just release a new version (6.11.0), you can fetch all tagged photos.
Example here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/tagged-medias.php

Feedback appreciated 😄
