### ISSUE TITLE
Get video media src

### ISSUE THREAD

**Issue by lon9man** [pgrimaud/instagram-user-feed#24]
1. Is it possible to get video source for media?
2. how do you think what is the way do you use for getting media from GraphQl API (temporary available, strongly available, mistakely available)?

**Comment by pgrimaud** [comment]
Hello @lon9man 
Which version do you use? ^4.0 or ^5.0 ?
Do you have an example of feed with video source for media?

**Comment by lon9man** [comment]
for example 
feed: https://www.instagram.com/wearecasey/
post: https://www.instagram.com/p/Bl0zz0DFVut/

**Comment by pgrimaud** [comment]
Unfortunately, video source is not provided in user feed.
To retrieve video source url, you can fetch and parse https://www.instagram.com/p/MEDIA_ID/?__a=1.

e.g. for `wearecasey` https://www.instagram.com/p/Bl0zz0DFVut?__a=1
graphql > shortcode_media > video_url
