### ISSUE TITLE
userId integer overflowed

### ISSUE THREAD

**Issue by dejvidecz** [pgrimaud/instagram-user-feed#240]
userId is stored as integer
functions in Instagram\Api.php has userId argument as integer

Max integer value is 2147483647
But for example one of my ids is 6383308725 

So all methods with userId as argument not works for me :-)
And method $profile->getId()  instead of 6383308725  returns 2147483647

maybe it should be changed to float or string :)

**Comment by pgrimaud** [comment]
Hello, I guess you're running this package on 32bits env?

**Comment by dejvidecz** [comment]
Hello @pgrimaud, yes i am running on 32 bit environment. I've just implemented few new classes (changed int to string)  and it works great :)

**Comment by pgrimaud** [comment]
Ok, cool !
I won't add a compatibility with 32bits env on this lib, because it will create tons of breaking changes and add lot of useless lines of code.
