### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.instagram.com/` resulted in a `429 Too Many Requests` response:

### ISSUE THREAD

**Issue by thirdgarcia** [pgrimaud/instagram-user-feed#242]
**Version(s) affected**: x.y.z
6.11.0
**Description**  
Im using a proxy but im still having 429 error. Its working fine on my local but im having the error on our staging server

**How to reproduce**  
Code and/or config needed to reproduce your problem.

**Additional context**  
Optional: any other context about the problem: log messages, screenshots, etc.

**Comment by pgrimaud** [comment]
I'm totally aware of this error. How many requests did you do before getting this error?

**Comment by thirdgarcia** [comment]
Thanks for your reply. 

Im not sure how many request I made. The proxy is being used in two websites for the same purpose. The other one works fine.

I was able to resolve this issue by disabling the proxy in the website with error.

**Comment by pgrimaud** [comment]
Are you sure about the usage of your proxy? Could you paste the code you wrote?
It's pretty weird it works one 1 website and the not on the other one.

**Comment by nestl1ng** [comment]
Have the same problem and i don't use proxy. How can I solve this?

**Comment by nestl1ng** [comment]
I started using proxy today but that didn’t solve the problem

**Comment by karrarjasim** [comment]
@gergel0304 
What proxy provider are you using?

**Comment by karrarjasim** [comment]
> I changed proxy and everything works fine

What proxy provider are you using?
@gergel0304
