### ISSUE TITLE
Post a comment on Instagram post

### ISSUE THREAD

**Issue by mojtabaghaseemi** [pgrimaud/instagram-user-feed#243]
Hi, your library was the most complete library I saw, but the only problem is that it is not possible to leave a comment for their post.

Please leave the ability to post comments in the Instagram post. I really need it

**Comment by pgrimaud** [comment]
Hey, 

It's a good idea, I'll implement it very soon!

**Comment by pgrimaud** [comment]
Hello,

I just release a new version (6.12.0), you can post a message to media.
Example here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/post-comment.php

Feedback appreciated 😄

**Comment by noranyz** [comment]
[Snaptika](https://snaptika.com/) is a simple and efficient platform for downloading TikTok videos quickly. It offers a user-friendly interface, making it easy for anyone to save their favorite content without complications. With fast processing and reliable performance, Snaptika ensures that users can access and enjoy videos offline anytime. A very helpful tool for those who want convenience and simplicity in managing their TikTok content.

**Comment by johnsmith44438** [comment]
I came across APKPure while looking for Android applications, and I found the platform quite convenient. The app listings are well organized, making it easier to explore different options. href="https://apkpure.com/">https://apkpure.com/</a></p>
