### ISSUE TITLE
Instagram Highlights by URL

### ISSUE THREAD

**Issue by kdspeaks** [pgrimaud/instagram-user-feed#244]
Hi there,
so is it possible to get a highlights by its URL?
When we try to copy the highlight URL from the Instagram android app the URL is similar to `https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTI0NzM5NjQwNTgwNjYy?story_media_id=2562092988995888143_178537482&utm_medium=copy_link` and when we click that it goes to `https://www.instagram.com/stories/highlights/17924739640580662/` this.

So if direct fetching by url is not possible, is it possible to atleast get profile id or username from any of these link?
In the first link `story_media_id=2562092988995888143_178537482` actually contains the user id, but there is no assurance that user will copy paste the whole thing.

Check that [https://instafinsta.com/insta-stories-download](url) website again, it is able to fetch the highlights from the `https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTI0NzM5NjQwNTgwNjYy` even without the query string.

Thanks.

**Comment by pgrimaud** [comment]
Hello,

I just added a way to get link without query string in 6.12.1 : https://github.com/pgrimaud/instagram-user-feed/commit/3f82d9ec623133f0ce1087683f64c14f5513cc2f

You'll be able to fetch get the link of highlight folder here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/story-highlights.php#L26

**Comment by kdspeaks** [comment]
Thank you for the quick enhancement.
I will surely check that out,  but again, is it possible to get the user id or the actual highlights folder link with this shareable url : https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTI0NzM5NjQwNTgwNjYy?story_media_id=2562092988995888143_178537482&utm_medium=copy_link

**Comment by pgrimaud** [comment]
I added 2 new methods in 6.12.2 : 

- `$folder->getUserId()` to get the user id
- `$folder->getSharableUrl()` to get link as you need

😄

**Comment by kdspeaks** [comment]
Well that's very generous.
I want something in reverse.
Like something
`$api->getHighlightsByLink('url-of-the-highlights-folder');`

Or any instructions on how to achive the same thing manually?

**Comment by pgrimaud** [comment]
I can make a $api->getHighlightsById('id-for-the-highlights-folder') easily?
What do you think about it?

**Comment by kdspeaks** [comment]
I am trying to build something with url. So if it's possible by id, then can you guide how to fetch the id with a link like this: https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTI0NzM5NjQwNTgwNjYy?story_media_id=2562092988995888143_178537482&utm_medium=copy_link

**Comment by pgrimaud** [comment]
In your url, you can retrieve the id of folder like this :

```php
preg_match('/\/s\/(.+)\?/m', 'https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTI0NzM5NjQwNTgwNjYy?story_media_id=2562092988995888143_178537482&utm_medium=copy_link', $matches);
$id = explode(':', base64_decode($matches[1]))[1];
print_r($id);
```

**Comment by kdspeaks** [comment]
Great. Then that with the $api->getHighlightsById('id-for-the-highlights-folder') will make a perfect combination.

Thanks

**Comment by pgrimaud** [comment]
You could try the 6.12.3 version :)

Example here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/story-highlights-by-id-folder.php

**Comment by kdspeaks** [comment]
You are awesome. Thanks for the real quick update.
