### ISSUE TITLE
414 Request-URI Too Long

### ISSUE THREAD

**Issue by fkiraz** [pgrimaud/instagram-user-feed#25]
Hello i've started to use your project.

> foreach ($feed->getMedias() as $media) {
	echo '#id#' . $media->getId();
	echo "\n";
}
$endCursor = $feed->getEndCursor();
$api->setEndCursor($endCursor);
sleep(2);
echo "page2 " .$endCursor. "\n";

I wrote this code to get user's media page by page. After 3 successful pages i saw this error.

> Warning: fread(): SSL: An existing connection was forcibly closed by the remote host.
 in C:\php\vendor\guzzlehttp\psr7\src\Stream.php on line 218
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.instagram.com/graphql/query/?query_hash=42323d64886122307be10013ad2dcc44&variables=%7B%22id%22:%222111407363%22,%22first%22:%2212%22,%22after%22:%22AQCcFWd3FYAs8u_jqqmbpUOj0FikmnibvnzZ9JR7IaSvWpM7OOhThWdaYR0tIVdv6IzqwpJxq_TQup4j0AvxtAZS-CjfpLbIV9wGtsgTTFlncQ%22%7D` resulted in a `414 Request-URI Too Long` response in C:\php\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 C:\php\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 C:\php\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 C:\php\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 C:\php\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::Guz in C:\php\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

I can't parse more than 3 pages from any account. Tried on windows and linux, the result was same. Can you help me?

**Comment by pgrimaud** [comment]
Hello @fkiraz
Weird, which version of PHP do you used?

Url you called (https://www.instagram.com/graphql/query/?query_hash=42323d64886122307be10013ad2dcc44&variables=%7B%22id%22:%222111407363%22,%22first%22:%2212%22,%22after%22:%22AQCcFWd3FYAs8u_jqqmbpUOj0FikmnibvnzZ9JR7IaSvWpM7OOhThWdaYR0tIVdv6IzqwpJxq_TQup4j0AvxtAZS-CjfpLbIV9wGtsgTTFlncQ%22%7D) is not very long (227 characters)

Can you past your entire script? I'm gonna try it on my side.

**Comment by fkiraz** [comment]
Thank you. I used PHP 7.2. Maybe i should try with PHP5?

PHP start tag didnt show up in quote.

> <?php

require 'C:\php\vendor\autoload.php';

if (!isset($argv[1])) {
	echo "No username specified\n";
	exit(1);
}

$cache = new Instagram\Storage\CacheManager('.\cache');
$api   = new Instagram\Api($cache);
$api->setUserName($argv[1]);
$feed = $api->getFeed();

foreach ($feed->getMedias() as $media) {
	echo '#id#' . $media->getId();
	echo "\n";
}
$endCursor = $feed->getEndCursor();
$api->setEndCursor($endCursor);
sleep(2);
echo "page2 " .$endCursor. "\n";
$feed = $api->getFeed();
foreach ($feed->getMedias() as $media) {
	echo '#id#' . $media->getId();
	echo "\n";
}
$endCursor = $feed->getEndCursor();
$api->setEndCursor($endCursor);
sleep(2);
echo "page3 " .$endCursor. "\n";
$feed = $api->getFeed();
foreach ($feed->getMedias() as $media) {
	echo '#id#' . $media->getId();
	echo "\n";
}
$endCursor = $feed->getEndCursor();
$api->setEndCursor($endCursor);
sleep(2);
echo "page4 " .$endCursor. "\n";
$feed = $api->getFeed();
foreach ($feed->getMedias() as $media) {
	echo '#id#' . $media->getId();
	echo "\n";
}
$endCursor = $feed->getEndCursor();
$api->setEndCursor($endCursor);
sleep(2);
echo "page5 " .$endCursor. "\n";
$feed = $api->getFeed();
?>

**Comment by pgrimaud** [comment]
I ran your script on PHP 5.6 and PHP 7.2 and it worked perfectly, on MacOSX and Linux (Debian).

Could you try with another IP?
