### ISSUE TITLE
videoUrl is empty !

### ISSUE THREAD

**Issue by RoseGoli** [pgrimaud/instagram-user-feed#252]
**Version(s) affected**: 6.12.3

**Description** 
Hi
Im trying to get a sigle post(not slides) from instagram but the lib just return the displayUrl and my post is a video !

**How to reproduce**  
```
Method      : getMediaDetailed
Empty index : videoUrl
```
Also this is one of the urls im testing on :
https://www.instagram.com/p/CSzJWVrjET3

And this is the method result ⏬ 

![Photo](https://user-images.githubusercontent.com/70085500/135714524-1571c99e-e472-4028-b52a-f3e3c8c26354.jpg)

Hope you can help me 🤞

**Comment by 89z** [comment]
I have another tool that works:

~~~
PS C:\> instagram -i CSzJWVrjET3
GET /p/CSzJWVrjET3/?__a=1 HTTP/1.1
Host: www.instagram.com
User-Agent: Instagram 207.0.0.39.120 Android

{Display_URL:https://scontent-dfw5-2.cdninstagram.com/v/t51.2885-15/e35/239442749_853162922240768_4409171677314399604_n.jpg?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_cat=108&_nc_ohc=spYjeEvCOBkAX8uIJG1&edm=AABBvjUBAAAA&ccb=7-4&oh=0401c6acecaf1bdd5539f5c970b7b803&oe=615D1394&_nc_sid=83d603
Edge_Sidecar_To_Children:<nil>
Video_URL:https://scontent-dfw5-2.cdninstagram.com/v/t50.2886-16/240181430_273557790860982_6418550365551512541_n.mp4?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_cat=106&_nc_ohc=rnf6JBwo4M4AX_nmPAX&edm=AABBvjUBAAAA&ccb=7-4&oe=615D00FF&oh=5a1b65e5955f989124c3dc99bb3d84b9&_nc_sid=83d603}
~~~

https://github.com/89z/mech

**Comment by RoseGoli** [comment]
> I have another tool that works:
> 
> ```
> PS C:\> instagram -i CSzJWVrjET3
> GET /p/CSzJWVrjET3/?__a=1 HTTP/1.1
> Host: www.instagram.com
> User-Agent: Instagram 207.0.0.39.120 Android
> 
> {Display_URL:https://scontent-dfw5-2.cdninstagram.com/v/t51.2885-15/e35/239442749_853162922240768_4409171677314399604_n.jpg?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_cat=108&_nc_ohc=spYjeEvCOBkAX8uIJG1&edm=AABBvjUBAAAA&ccb=7-4&oh=0401c6acecaf1bdd5539f5c970b7b803&oe=615D1394&_nc_sid=83d603
> Edge_Sidecar_To_Children:<nil>
> Video_URL:https://scontent-dfw5-2.cdninstagram.com/v/t50.2886-16/240181430_273557790860982_6418550365551512541_n.mp4?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_cat=106&_nc_ohc=rnf6JBwo4M4AX_nmPAX&edm=AABBvjUBAAAA&ccb=7-4&oe=615D00FF&oh=5a1b65e5955f989124c3dc99bb3d84b9&_nc_sid=83d603}
> ```
> 
> https://github.com/89z/mech

Well i need to done this with this lib
All of my codes based on it
Tnx for your reply🙏
