### ISSUE TITLE
Get hd profile photo by username

### ISSUE THREAD

**Issue by RoseGoli** [pgrimaud/instagram-user-feed#253]
Hi

Could you add hd_profile_pic_url_info to getProfile method ?

In that way we can load users high quality profile picture fast and easy by username ...

I think the only way at this time is to getProfile first, to get thr user id and then use getProfileAlternative .
But this is not a good way because of multiple request 😶

Tnx for your amazing lib 🤍🌸

**Comment by 89z** [comment]
Can you provide example profile

**Comment by RoseGoli** [comment]
> Can you provide example profile

If we have the username "google"
Then we can get the photo url by this code :

```
$inf   = $api->getProfile($match[1])->toArray();
$photo = $inf['profilePicture'];
```

But this is not the hd profile picture !
Lets see the quality
![IMG_20211005_093345_219](https://user-images.githubusercontent.com/70085500/135969066-5908dc95-6a0d-4770-966a-0a0738eca698.jpg)

But this is the hd one . . .

![IMG_20211005_093508_747](https://user-images.githubusercontent.com/70085500/135969228-7ce38583-74f4-47f0-bd3d-b123a11b45cd.jpg)
