### ISSUE TITLE
Fatal error</b>:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: www.instagram.com

### ISSUE THREAD

**Issue by jolsebastian** [pgrimaud/instagram-user-feed#254]
**Version(s) affected**: 
"pgrimaud/instagram-user-feed": "^6.12"
PHP 8

**Description**  
<br />
<b>Fatal error</b>:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: www.instagram.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.instagram.com/ in site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client-&gt;transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client-&gt;requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#13 site.com/dev/pgrimaud/vendor/pgrimaud/instagram-user-feed/src/Instagram/Auth/Login.php(66): GuzzleHttp\Client-&gt;request('GET', 'https://www.ins...', Array)
#14 site.com/dev/pgrimaud/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(126): Instagram\Auth\Login-&gt;process()
#15 site.com/dev/pgrimaud/index.php(23): Instagram\Api-&gt;login('user', 'pass')
#16 {main}
  thrown in <b>site.com/dev/pgrimaud/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php</b> on line <b>210</b><br />

**How to reproduce**  
I created an instagram account a few months ago. it is public profile. without MFA. I was notified that my account was accessed and I allowed it.

And this is my code:
`<?php
require __DIR__ . '/vendor/autoload.php';
use Instagram\Api;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');

$api = new Api($cachePool);
$api->login('username', 'pass'); // mandatory
$profile = $api->getProfile('username');

echo $profile->getUserName(); // robertdowneyjr

echo $profile->getFullName(); // Robert Downey Jr. Official`

**Possible Solution**  
Nothing yet

**Comment by pechondra** [comment]
Maby good point fot resolve this issue => option for set cURL request timeout in `pgrimaud/instagram-user-feed`?

does not solve this problem but, you can respond to an exception and will not block web loading...

**Comment by RoseGoli** [comment]
Are you sure that this problem is not about instagram issues ?
Last night instagram and facebook were down 🤨

**Comment by RoseGoli** [comment]
Are you sure that this problem is not about instagram issues ?
Last night instagram and facebook were down 🤨

![Screenshot](https://user-images.githubusercontent.com/70085500/135970216-0f93d119-0993-4f66-8741-8f7f4e536914.jpg)

**Comment by pechondra** [comment]
@RoseGoli Yes, but my websites was loading long time becose web waiting for request on instagram. This is bad expirience for my. 😢
Yes, this problem have another solition, for example download images and next data in cron task to my webserver and using data of my server for view but...

**Comment by pgrimaud** [comment]
Hello,

Yes, if your website il calling the API each time you load a page, the basic way is to add a timeout in the client to avoid blocking. Or to call the API with async requests (ajax or crontabs).
