### ISSUE TITLE
Fatal error: Uncaught TypeError: Return value of Instagram\Transport\JsonMediaDetailedDataFeed::fetchData() must be an instance of stdClass, null returned

### ISSUE THREAD

**Issue by eldark** [pgrimaud/instagram-user-feed#258]
**Version(s) affected**: 6.12.3

**Description**  
I started getting this error:
```
Fatal error: Uncaught TypeError: Return value of Instagram\Transport\JsonMediaDetailedDataFeed::fetchData() must be an instance of stdClass, null returned in /var/www/html/instagram-user-feed/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/JsonMediaDetailedDataFeed.php:23
```

**How to reproduce**  
Just using the API following the examples.

**Possible Solution**  
~~The '?__a=1' trick might not work anymore:~~

```php
public function fetchData(Media $media): \StdClass
    {
        $data = $this->fetchJsonDataFeed($media->getLink() . '?__a=1');

        return $data->graphql;
    }
```

**Comment by eldark** [comment]
This has started happening again, with all the new accounts I've created.

**Comment by yavarnia** [comment]
Hello and thanks for your great package.

I started getting this error when an Instagram account has a gallery post item with "GraphSidecar" or "GraphVideo" media type in their posts list.
I am using the latest version.

Fatal error: Uncaught TypeError: Return value of Instagram\Transport\JsonMediaDetailedDataFeed::fetchData() must be an instance of stdClass, null returned
