### ISSUE TITLE
New Issue - Guzzle Curl 18

### ISSUE THREAD

**Issue by frisch1** [pgrimaud/instagram-user-feed#26]
Hello...
Great package, thank you. I'm hitting a consistent error. You can repeat this on:

	$api->setUserName('repbarbaracomstock');

When using the end cursor function, it'll work for the first 2-4 times. Then it'll hit this error:

PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 18: transfer closed with outstanding read data remaining (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/ubuntu/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

The error is the size returned doesn't match what was reported. 

Is there a way to ignore this error? The try/catch doesn't catch this one...

Update. I'm catching the error now. The exception it throws is:
cURL error 18: transfer closed with outstanding read data remaining (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

The Google recommendation is to ignore the filesize reported if possible.

**Comment by pgrimaud** [comment]
Weird, damn!

What is the version of your curl package? `curl --version`
PHP version? `php -v`
php-curl-ext? `php -r 'print_r(curl_version());'`

I guess you can catch this error with `RequestException`.

**Comment by gtapps** [comment]
I'm having  the same issue when using pagination:
curl 7.61.0
PHP 7.2.15
php curl ext: 474368
