### ISSUE TITLE
GetLocation method throws an exception

### ISSUE THREAD

**Issue by floor12** [pgrimaud/instagram-user-feed#260]
**Version(s) affected**: 6.12.3

**Description**  
Looks like Instagram changed they api...

I got exception when trying to load location data by id.

> PHP Warning 'yii\base\ErrorException' with message 'Attempt to read property "location" on null' 
> 
> in /app/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/LocationData.php:54
> 
> Stack trace:
> #0 /app/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/LocationData.php(54): yii\base\ErrorHandler->handleError(2, 'Attempt to read...', '/app/vendor/pgr...', 54)
> #1 /app/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(575): Instagram\Transport\LocationData->fetchData(196091681061421)
> #2 /app/components/GeoTagHelper.php(19): Instagram\Api->getLocation(196091681061421)

**How to reproduce**  
Load location data with ID 196091681061421; 
```php 
$api->getLocation(196091681061421);
```

**Possible Solution**  
The   `graphql`  response section is empty now. The response  has a new structure...   The LocationData and LocationHydrator classes need to be updated...

**Comment by honkkki** [comment]
PHP Notice:  Undefined property: stdClass::$graphql in /mnt/d/linux/ins/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/JsonMediaDetailedDataFeed.php on line 23
PHP Fatal error:  Uncaught TypeError: Return value of Instagram\Transport\JsonMediaDetailedDataFeed::fetchData() must be an instance of stdClass, null returned in /mnt/d/linux/ins/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/JsonMediaDetailedDataFeed.php:23
