### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by saeideros** [pgrimaud/instagram-user-feed#266]
**Version(s) affected**: 6.12.3

Fatal error: Uncaught TypeError: Return value of Instagram\Transport\JsonMediaDetailedDataFeed::fetchData() must be an instance of stdClass, null returned in /test/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/JsonMediaDetailedDataFeed.php:23

Stack trace:

#0 /test/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(381): Instagram\Transport\JsonMediaDetailedDataFeed->fetchData(Object(Instagram\Model\Media))

#1 /test/test.php(24): Instagram\Api->getMediaDetailed(Object(Instagram\Model\Media))

#2 {main} thrown in /test/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/JsonMediaDetailedDataFeed.php on line 23

**Comment by cookieguru** [comment]
I am working on this

**Comment by eldark** [comment]
Also got this on #258

**Comment by ksrupan** [comment]
> I am working on this

Hi, Please give the approximate date to get the solution for this fatal error issue.

**Comment by cookieguru** [comment]
@ksrupan That's not how open source works.  You're welcome to take a stab at it yourself and open a PR

**Comment by cookieguru** [comment]
Fixed in #269
Sorry I was not able to contribute due to health issues
