### ISSUE TITLE
Fatal error: Uncaught TypeError: Return value of Instagram\Transport\JsonMediaDetailedDataFeed::fetchData() must be an instance of stdClass, null returned

### ISSUE THREAD

**Issue by yavarnia** [pgrimaud/instagram-user-feed#267]
**Version(s) affected**: 6.12.3

**Description**  
I started getting this error when an Instagram account has a gallery post item with "GraphSidecar" or "GraphVideo" media type in their posts list.

has failed TypeError: Return value of Instagram\Transport\JsonMediaDetailedDataFeed::fetchData() must be an instance of stdClass, null returned in pgrimaud/instagram-user-feed/src/Instagram/Transport/JsonMediaDetailedDataFeed.php:23

**How to reproduce**  
JsonMediaDetailedDataFeed.php:23 

`public function fetchData(Media $media): \StdClass
{
        $data = $this->fetchJsonDataFeed($media->getLink() . '?__a=1');
        return $data->graphql;
}`

**Additional context**  
I am using this line of code:

`foreach ( $medias as $media )
{
	$media_type = $media->getTypeName();
	
	if ( $media_type == 'GraphSidecar' || $media_type == 'GraphVideo' )		
		$media_detailed = $this->api->getMediaDetailed( $media );		
}`

**Comment by KamranKhorsandi** [comment]
Hi
I have this problem too.
please check it.

**Comment by pgrimaud** [comment]
Hello,

My server has been banned from the API who provided the Crypto prices.
I fixed it 2 days ago, sorry about the downtime :(

Best,

Pierre

**Comment by yavarnia** [comment]
> Hello,
> 
> My server has been banned from the API who provided the Crypto prices. I fixed it 2 days ago, sorry about the downtime :(
> 
> Best,
> 
> Pierre

Hello, 
Thanks for your efforts for this project, I am looking forward to receive your last changes.

**Comment by KamranKhorsandi** [comment]
Hello
Not updated yet?
My service has been down for 2 weeks :(
