### ISSUE TITLE
New instagram hashtags

### ISSUE THREAD

**Issue by binar123** [pgrimaud/instagram-user-feed#27]
Hashtags at instagram just changed how they work
Will u provide hashtags scrapper (if it exist in their api)

**Comment by pgrimaud** [comment]
Hi @binar123,

Unfortunately this package doesn't scrap any hashtags. It only scrap user feed.

**Comment by binar123** [comment]
i mean hashtags were moved from caption to idk where

**Comment by pgrimaud** [comment]
When I execute the file `examples/medias.php` I can see : 

```
ID        : 1855305733072311817
Caption   : Ola ! #casino #paella #ept #pokerstars
Link      : https://www.instagram.com/p/Bm_XrwBhVYJ/
Likes     : 24
Date      : 2018-08-27 05:08:20
```

So I guess hashtags didn't moved.

Do you have an example where hashtags moved from caption?

**Comment by binar123** [comment]
many of photos posted today doesnt have hashtags included in caption but within hashtag search they are there. i read also a post somewhere but couldnt find it now

**Comment by pgrimaud** [comment]
Ok, can you give ma an example of a specific post?

**Comment by binar123** [comment]
https://www.instagram.com/p/BoE5x_Fga2J/?utm_source=ig_web_button_share_sheet it appears in #inked #ink hashtags

**Comment by binar123** [comment]
also this reefers to it https://twitter.com/wongmjane/status/1042641926678167552/photo/1?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1042641926678167552%7Ctwgr%5E383231323b636f6e74726f6c&ref_url=https%3A%2F%2Fwww.eska.pl%2Fnews%2Finstagram-hasztagi-znikna-serwis-rozpoczal-testy-aa-mhoa-D9cU-2cYG.html

**Comment by pgrimaud** [comment]
Ok, I can't find any hashtags into https://www.instagram.com/p/BoE5x_Fga2J 😞
I think hashtags are registered server side.

So I can't fetch it... for the moment.

```
Instagram is testing the ability to add hashtags to posts without including it in the post caption
```

Let's see if Instagram will release this feature soon.
