### ISSUE TITLE
"Syntax error" on getMediaDetailed & getMediaDetailedByShortCode

### ISSUE THREAD

**Issue by andykamezou** [pgrimaud/instagram-user-feed#293]
**Version(s) affected**: 6.15.0

**Description**  
When running the script, "Syntax error" is printed at `$mediaDetailed = $api->getMediaDetailed($media);` or `$mediaDetailed = $api->getMediaDetailedByShortCode($media);` . Commented these line and "Syntax error" will not appear anymore.

**How to reproduce**  
I tried both separately, based on the sample provided in the "examples" folder. Literally copy and paste, and run the script. With credential setup which is confirmed working as expected on other API call such as `getProfile()`.

**Side note**  
This is my first few hours of testing this library. I'm trying to figure out how to get all the data of multiple photos from one carousel. The documentation wasn't very clear if this API call is what I actually need. Even `downloadMedia()` seems to only download the first photo of the carousel. I'd be grateful for some guidance.

**Comment by nagajoomlapro** [comment]
Hello @andykamezou, Thanks for your wonderfull extension. its awesome.   me also facing same issue. i cant get media url.  got "Syntax error".   Kindly check with this issue.
Advance Thanks
