### ISSUE TITLE
feedback_required !

### ISSUE THREAD

**Issue by armanvid** [pgrimaud/instagram-user-feed#297]
Client error: `POST https://www.instagram.com/web/friendships/3118475194/unfollow/` resulted in a `400 Bad Request` response: {"message":"feedback_required","spam":true,"feedback_title":"Try Again Later","feedback_message":"We restrict certain ac (truncated...)
i get this error
how i can fix it?

**Comment by cookieguru** [comment]
I'm not certain since you truncated the message but it looks like you are sending too many requests in a short amount of time.  Try waiting longer in between requests, and set up exponential backoff if you continue receive this error.

**Comment by pgrimaud** [comment]
> Try waiting longer in between requests, and set up exponential backoff if you continue receive this error.

^ This. Or use proxies.
