### ISSUE TITLE
Pagination doesn't work anymore

### ISSUE THREAD

**Issue by pgrimaud** [pgrimaud/instagram-user-feed#3]
end_cursor seems to still work on tags : https://www.instagram.com/explore/tags/space/?__a=1&max_id=AQA6xcax1Of8qjYhYiW8LQVhtp6dwFWI6dZc6ry4JiPnCWMhx7SOYk31aUlfNu36Zh6qjjqOH2JNxGRTbMu3aY22BCTZW5cmV_5S2v73VCXBPQ

@jannejava

**Comment by pgrimaud** [comment]
Fixed in 2.1.0 https://github.com/pgrimaud/instagram-user-feed/releases/tag/2.1.0

**Comment by jannejava** [comment]
Good work!
