### ISSUE TITLE
version problem installing guzzlehttp/guzzle "^5.0"

### ISSUE THREAD

**Issue by acaparrelli** [pgrimaud/instagram-user-feed#30]
Hi, I'm trying to install version "^5.0" (I also tried version "^4.0") and I'm getting this error:

```
$ composer require pgrimaud/instagram-user-feed "^5.0"

Problem 1
    - pgrimaud/instagram-user-feed 5.1.3 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.3.x-dev] but these conflict with your requirements or minimum-stability.
    - pgrimaud/instagram-user-feed 5.1.2 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.3.x-dev] but these conflict with your requirements or minimum-stability.
    - pgrimaud/instagram-user-feed 5.1.1 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.3.x-dev] but these conflict with your requirements or minimum-stability.
    - pgrimaud/instagram-user-feed 5.1.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.3.x-dev] but these conflict with your requirements or minimum-stability.
    - pgrimaud/instagram-user-feed 5.0.1 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.3.x-dev] but these conflict with your requirements or minimum-stability.
    - pgrimaud/instagram-user-feed 5.0.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for pgrimaud/instagram-user-feed ^5.0 -> satisfiable by pgrimaud/instagram-user-feed[5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.1.3].

```
If I'm not wrong it seems to be that composer is not taking 6.3.0 version as a good version because os the missing "0" in the instagram-user-feed's composer.json ?

Thank you.

**Comment by pgrimaud** [comment]
Hi @acaparrelli 

I guess you try to add this dependency to an existing project? 
Can you show me the file composer.json of this project?

**Comment by acaparrelli** [comment]
That's correct @pgrimaud could I send you my composer.json, via private message? Maybe to the email on your personal webpage?

Thanks

**Comment by pgrimaud** [comment]
@acaparrelli Yes, to the email of my personal webpage.

**Comment by pgrimaud** [comment]
The version of Guzzle in this package is ^6.3

Your composer.json has fixed dependency requirement of Guzzle `"guzzlehttp/guzzle": "~5.0"` which is and old version, initially released in 2014 but maintained.

So if you want to use this package into your app, you should also update your dependency `csa/guzzle-bundle`.

Hope it helps

**Comment by acaparrelli** [comment]
Thank you for your time @pgrimaud. I will check that.
Have a good day!
