### ISSUE TITLE
__d=dis forgotten in JsonMediaDetailedDataFeed Class For Get Media's Details 

### ISSUE THREAD

**Issue by mimesm** [pgrimaud/instagram-user-feed#300]
hi pierre i think you forget to add __d=dis variable to JsonMediaDetailedDataFeed class and data must be null because this issue 

Friends You Can Add manually **&__d=dis** after __a too solve this problem until package update

**Comment by pgrimaud** [comment]
Thank you. This have be fixed in 6.15.2 😄
