### ISSUE TITLE
get media by url

### ISSUE THREAD

**Issue by mamadjavadrasty** [pgrimaud/instagram-user-feed#301]
Hello, don't be tired
Thank you for your good package
If you can, add the possibility to download the post with a link

**Comment by nsmle** [comment]
Hi @mamadjavadrasty, is the [MediaDownloadHelper](https://github.com/pgrimaud/instagram-user-feed/blob/master/src/Instagram/Utils/MediaDownloadHelper.php#L9-L29) helper not working?
See an example of its use at file [examples/medias-download.php](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/medias-download.php#L36L38)
