### ISSUE TITLE
getProfile() error

### ISSUE THREAD

**Issue by gergel0304** [pgrimaud/instagram-user-feed#302]
Hi! I have error when try to do:

`$profile = $api->getProfile($username);`

**Error: Syntax error**

var_dump($e) show this:

`object(Instagram\Exception\InstagramFetchException)#96 (7) { ["message":protected]=> string(19) "Error: Syntax error" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(133) "/home/g/gergel/insta.gergel.pro/public_html/lib/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/JsonProfileDataFeedV2.php" ["line":protected]=> int(28) ["trace":"Exception":private]=> array(3) { [0]=> array(6) { ["file"]=> string(105) "/home/g/gergel/insta.gergel.pro/public_html/lib/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php" ["line"]=> int(723) ["function"]=> string(9) "fetchData" ["class"]=> string(41) "Instagram\Transport\JsonProfileDataFeedV2" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> string(10) "fruktoshop" } } [1]=> array(6) { ["file"]=> string(58) "/home/g/gergel/insta.gergel.pro/public_html/app/update.php" ["line"]=> int(75) ["function"]=> string(10) "getProfile" ["class"]=> string(13) "Instagram\Api" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> string(10) "fruktoshop" } } [2]=> array(4) { ["file"]=> string(56) "/home/g/gergel/insta.gergel.pro/public_html/app/show.php" ["line"]=> int(145) ["args"]=> array(1) { [0]=> string(58) "/home/g/gergel/insta.gergel.pro/public_html/app/update.php" } ["function"]=> string(7) "include" } } ["previous":"Exception":private]=> NULL }`

var_dump($api) show this:

`object(Instagram\Api)#23 (4) { ["cachePool":protected]=> object(Symfony\Component\Cache\Adapter\FilesystemAdapter)#7 (13) { ["namespace":"Symfony\Component\Cache\Adapter\AbstractAdapter":private]=> string(0) "" ["defaultLifetime":"Symfony\Component\Cache\Adapter\AbstractAdapter":private]=> int(0) ["namespaceVersion":"Symfony\Component\Cache\Adapter\AbstractAdapter":private]=> string(0) "" ["versioningIsEnabled":"Symfony\Component\Cache\Adapter\AbstractAdapter":private]=> bool(false) ["deferred":"Symfony\Component\Cache\Adapter\AbstractAdapter":private]=> array(0) { } ["ids":"Symfony\Component\Cache\Adapter\AbstractAdapter":private]=> array(1) { ["instagram.session.finiki_optom_ru"]=> string(33) "instagram.session.finiki_optom_ru" } ["maxIdLength":protected]=> NULL ["logger":protected]=> NULL ["callbackWrapper":"Symfony\Component\Cache\Adapter\AbstractAdapter":private]=> array(2) { [0]=> string(36) "Symfony\Component\Cache\LockRegistry" [1]=> string(7) "compute" } ["computing":"Symfony\Component\Cache\Adapter\AbstractAdapter":private]=> array(0) { } ["marshaller":"Symfony\Component\Cache\Adapter\FilesystemAdapter":private]=> object(Symfony\Component\Cache\Marshaller\DefaultMarshaller)#6 (1) { ["useIgbinarySerialize":"Symfony\Component\Cache\Marshaller\DefaultMarshaller":private]=> bool(false) } ["directory":"Symfony\Component\Cache\Adapter\FilesystemAdapter":private]=> string(60) "/home/g/gergel/insta.gergel.pro/public_html/cache/Instagram/" ["tmp":"Symfony\Component\Cache\Adapter\FilesystemAdapter":private]=> NULL } ["client":protected]=> object(GuzzleHttp\Client)#8 (1) { ["config":"GuzzleHttp\Client":private]=> array(9) { ["proxy"]=> array(1) { ["https"]=> string(39) "pZwSkaNt:2CKww4hP@195.208.118.124:61640" } ["handler"]=> object(GuzzleHttp\HandlerStack)#11 (3) { ["handler":"GuzzleHttp\HandlerStack":private]=> object(Closure)#18 (2) { ["static"]=> array(2) { ["default"]=> object(Closure)#16 (2) { ["static"]=> array(2) { ["default"]=> object(GuzzleHttp\Handler\CurlMultiHandler)#12 (6) { ["factory":"GuzzleHttp\Handler\CurlMultiHandler":private]=> object(GuzzleHttp\Handler\CurlFactory)#13 (2) { ["handles":"GuzzleHttp\Handler\CurlFactory":private]=> array(0) { } ["maxHandles":"GuzzleHttp\Handler\CurlFactory":private]=> int(50) } ["selectTimeout":"GuzzleHttp\Handler\CurlMultiHandler":private]=> int(1) ["active":"GuzzleHttp\Handler\CurlMultiHandler":private]=> NULL ["handles":"GuzzleHttp\Handler\CurlMultiHandler":private]=> array(0) { } ["delays":"GuzzleHttp\Handler\CurlMultiHandler":private]=> array(0) { } ["options":"GuzzleHttp\Handler\CurlMultiHandler":private]=> array(0) { } } ["sync"]=> object(GuzzleHttp\Handler\CurlHandler)#14 (1) { ["factory":"GuzzleHttp\Handler\CurlHandler":private]=> object(GuzzleHttp\Handler\CurlFactory)#15 (2) { ["handles":"GuzzleHttp\Handler\CurlFactory":private]=> array(0) { } ["maxHandles":"GuzzleHttp\Handler\CurlFactory":private]=> int(3) } } } ["parameter"]=> array(2) { ["$request"]=> string(10) "" ["$options"]=> string(10) "" } } ["streaming"]=> object(GuzzleHttp\Handler\StreamHandler)#17 (1) { ["lastHeaders":"GuzzleHttp\Handler\StreamHandler":private]=> array(0) { } } } ["parameter"]=> array(2) { ["$request"]=> string(10) "" ["$options"]=> string(10) "" } } ["stack":"GuzzleHttp\HandlerStack":private]=> array(4) { [0]=> array(2) { [0]=> object(Closure)#19 (2) { ["static"]=> array(1) { ["bodySummarizer"]=> NULL } ["parameter"]=> array(1) { ["$handler"]=> string(10) "" } } [1]=> string(11) "http_errors" } [1]=> array(2) { [0]=> object(Closure)#20 (1) { ["parameter"]=> array(1) { ["$handler"]=> string(10) "" } } [1]=> string(15) "allow_redirects" } [2]=> array(2) { [0]=> object(Closure)#21 (1) { ["parameter"]=> array(1) { ["$handler"]=> string(10) "" } } [1]=> string(7) "cookies" } [3]=> array(2) { [0]=> object(Closure)#22 (1) { ["parameter"]=> array(1) { ["$handler"]=> string(10) "" } } [1]=> string(12) "prepare_body" } } ["cached":"GuzzleHttp\HandlerStack":private]=> NULL } ["allow_redirects"]=> array(5) { ["max"]=> int(5) ["protocols"]=> array(2) { [0]=> string(4) "http" [1]=> string(5) "https" } ["strict"]=> bool(false) ["referer"]=> bool(false) ["track_redirects"]=> bool(false) } ["http_errors"]=> bool(true) ["decode_content"]=> bool(true) ["verify"]=> bool(true) ["cookies"]=> bool(false) ["idn_conversion"]=> bool(false) ["headers"]=> array(1) { ["User-Agent"]=> string(12) "GuzzleHttp/7" } } } ["session":protected]=> object(Instagram\Auth\Session)#39 (1) { ["cookies":"Instagram\Auth\Session":private]=> object(GuzzleHttp\Cookie\CookieJar)#25 (2) { ["cookies":"GuzzleHttp\Cookie\CookieJar":private]=> array(12) { [0]=> object(GuzzleHttp\Cookie\SetCookie)#26 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(9) "csrftoken" ["Value"]=> string(32) "P1NETaRAN3sljxt1WnOj1zbbIGWJki6t" ["Domain"]=> string(14) ".instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(8) "31449600" ["Expires"]=> int(1666332123) ["Secure"]=> bool(true) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } [1]=> object(GuzzleHttp\Cookie\SetCookie)#27 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(3) "rur" ["Value"]=> string(3) "ASH" ["Domain"]=> string(14) ".instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> NULL ["Expires"]=> NULL ["Secure"]=> bool(true) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(true) } } [2]=> object(GuzzleHttp\Cookie\SetCookie)#28 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(3) "mid" ["Value"]=> string(28) "YXJT2QAEAAE3p49HLQCyuvMnruTs" ["Domain"]=> string(14) ".instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(8) "63072000" ["Expires"]=> int(1697954523) ["Secure"]=> bool(true) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } [3]=> object(GuzzleHttp\Cookie\SetCookie)#29 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(10) "ds_user_id" ["Value"]=> string(11) "44117152041" ["Domain"]=> string(14) ".instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(7) "7776000" ["Expires"]=> int(1642658523) ["Secure"]=> bool(true) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } [4]=> object(GuzzleHttp\Cookie\SetCookie)#30 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(9) "sessionid" ["Value"]=> string(33) "44117152041%3ASzdB76oDlXgIn2%3A18" ["Domain"]=> string(14) ".instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(8) "31536000" ["Expires"]=> int(1666418523) ["Secure"]=> bool(true) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(true) } } [5]=> object(GuzzleHttp\Cookie\SetCookie)#31 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(6) "ig_did" ["Value"]=> string(36) "2256D42E-0075-4EA0-8EDE-DFDDD2FEB692" ["Domain"]=> string(14) ".instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(8) "63072000" ["Expires"]=> int(1697954523) ["Secure"]=> bool(true) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(true) } } [6]=> object(GuzzleHttp\Cookie\SetCookie)#32 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(5) "ig_cb" ["Value"]=> string(2) """" ["Domain"]=> string(13) "instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(1) "0" ["Expires"]=> int(0) ["Secure"]=> bool(false) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } [7]=> object(GuzzleHttp\Cookie\SetCookie)#33 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(5) "ig_cb" ["Value"]=> string(2) """" ["Domain"]=> string(14) ".instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(1) "0" ["Expires"]=> int(0) ["Secure"]=> bool(false) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } [8]=> object(GuzzleHttp\Cookie\SetCookie)#34 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(5) "ig_cb" ["Value"]=> string(2) """" ["Domain"]=> string(15) "i.instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(1) "0" ["Expires"]=> int(0) ["Secure"]=> bool(false) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } [9]=> object(GuzzleHttp\Cookie\SetCookie)#35 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(5) "ig_cb" ["Value"]=> string(2) """" ["Domain"]=> string(16) ".i.instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(1) "0" ["Expires"]=> int(0) ["Secure"]=> bool(false) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } [10]=> object(GuzzleHttp\Cookie\SetCookie)#36 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(5) "ig_cb" ["Value"]=> string(2) """" ["Domain"]=> string(17) "www.instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(1) "0" ["Expires"]=> int(0) ["Secure"]=> bool(false) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } [11]=> object(GuzzleHttp\Cookie\SetCookie)#37 (1) { ["data":"GuzzleHttp\Cookie\SetCookie":private]=> array(9) { ["Name"]=> string(5) "ig_cb" ["Value"]=> string(2) """" ["Domain"]=> string(18) ".www.instagram.com" ["Path"]=> string(1) "/" ["Max-Age"]=> string(1) "0" ["Expires"]=> int(0) ["Secure"]=> bool(false) ["Discard"]=> bool(false) ["HttpOnly"]=> bool(false) } } } ["strictMode":"GuzzleHttp\Cookie\CookieJar":private]=> bool(false) } } ["challengeDelay":protected]=> int(3) }`

I have last 6.14 version, after update it works fine, but some time ago it start to show this error. Help please, what is wrong. Thank you!!

**Comment by pgrimaud** [comment]
This issue have been resolved in `^6.15`, please update to this version

**Comment by gergel0304** [comment]
It works! Thank you!

**Comment by nestl1ng** [comment]
I updated to version 6.15.2, but the error has not gone away. I connected the proxy, it worked for 5 minutes, and then again. I tried different proxies. Help me please

**Comment by fiction13** [comment]
I have the same error even after updating to version 6.15.2.
