### ISSUE TITLE
Too Many Requests Error

### ISSUE THREAD

**Issue by harshanasrimal** [pgrimaud/instagram-user-feed#303]
**Version(s) affected**: 6.15

**Description**  
Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 Too Many Requests` response: {"message":"","status":"fail"}

**How to reproduce**  
Try 10-20 requests within 1 minute and see.

**Comment by pgrimaud** [comment]
The only way to avoid it is to use proxies.
