### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: Connection refused

### ISSUE THREAD

**Issue by bugbaal** [pgrimaud/instagram-user-feed#306]
**Version(s) affected**:
6.15

**Description**  
If I use the proxy I get the error in the title description, if I don't use the proxy I get the following message:
"Generic error \ Your IP may be block from Instagram. You should consider using a proxy".

**How to reproduce**  
                cachePool = new FilesystemAdapter('instagram', 0, __DIR__ . '/cache');
                $client = new Client
                ([
                    'proxy' =>
                    [
                         "https" => "xx.xx.191.60:xxxx",
                    ]
                ]);

                $data   = $client->request('GET', 'https://api.ipify.org?format=json');
                $dataIp = json_decode((string)$data->getBody());
                $dataRealIp = json_decode(file_get_contents('https://api.ipify.org?format=json'));
                api = new Api( cachePool, $client );

** Full error message **:
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: Connection refused for URI https://www.instagram.com/accounts/login/ajax/ in /var/www/html/instagram/instagram-user-feed/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:328 Stack trace: #0 /var/www/html/instagram/instagram-user-feed/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(241): GuzzleHttp\Handler\StreamHandler->GuzzleHttp\Handler\{closure}() #1 /var/www/html/instagram/instagram-user-feed/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(339): GuzzleHttp\Handler\StreamHandler->createResource() #2 /var/www/html/instagram/instagram-user-feed/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(58): GuzzleHttp\Handler\StreamHandler->createStream() #3 /var/www/html/instagram/instagram-user-feed/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\StreamHandler->__invoke() #4 /var/www/html/instagram/instagram-user-feed/vendor/guzzlehttp/guzzle/src/Middleware.php(37): GuzzleHttp\PrepareBodyMiddleware->__invoke() #5 in /var/www/html/instagram/instagram-user-feed/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php on line 72

thanks in advance

**Comment by pgrimaud** [comment]
I guess this issue was resolved (cf #307)?
