### ISSUE TITLE
Set medias number per page

### ISSUE THREAD

**Issue by fagnanigm** [pgrimaud/instagram-user-feed#32]
Hey guys, 

How can I limit the number of my medias by 10 per "page"? I have 41 medias in total, and I would like paginate by 4 or 5 pages with only 10 medias.

**Comment by pgrimaud** [comment]
Hey @fagnanigm,

Unfortunately, it's not possible.
First, this scraper retrieve the 12 last medias from an Instagram account.
Then, it scrapes the 12 next medias from Instagram json feed. And etc.

If you want to paginate with only 10 medias, you must do it on your side.

**Comment by fagnanigm** [comment]
@pgrimaud , that's ok!

Thank you for your helpful! On the other hand, congratulation about this code and api, it amazing! Thanks! 

👍

**Comment by pgrimaud** [comment]
No problem, I hope this package helps you in any way!
