### ISSUE TITLE
400 Bad Request error when trying to get profile by id

### ISSUE THREAD

**Issue by AgentSmith0** [pgrimaud/instagram-user-feed#326]
**Version(s) affected**: 6.16.1

**Description**  
When trying to get a profile by id, I get the following error message:
`Error: Client error: 'GET https://i.instagram.com/api/v1/users/web_profile_info/?username=robertdowneyjr' resulted in a '400 Bad Request' response: {"message":"useragent mismatch","status":"fail"}`

**How to reproduce**  
Try this example: https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/profile-by-id.php

**Comment by wkeles** [comment]
amk cocuklari cevap versenize

**Comment by audreybzt** [comment]
+1
I have the same error even though the profile exists.
Version : 6.16.14

**Comment by felipegallo** [comment]
Same error! Does anyone have any ideas? It seems that there is some problem related to the useragent passed in the header.

**Comment by fmchan** [comment]
+1
I have the same error while calling checkpoint-challenge.php
