### ISSUE TITLE
ssl certificate problem?

### ISSUE THREAD

**Issue by mejuliver** [pgrimaud/instagram-user-feed#33]
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate

**Comment by pgrimaud** [comment]
Hi @mejuliver,

What is the version of your curl package? curl --version
PHP version? php -v
php-curl-ext? php -r 'print_r(curl_version());'

I guess you can catch this error with RequestException.

**Comment by mejuliver** [comment]
Tried your two versions, the one with version 4 and the second one version 5, I'm running php 5.6. version on the version 4 and php version 7.2 on the version 5 but same error. Any help, ideas please?

**Comment by pgrimaud** [comment]
What is the version of your curl package? 
```
curl --version
```
php-curl-ext? 
```
php -r 'print_r(curl_version());'
```

**Comment by mejuliver** [comment]
@pgrimaud version  7.61.1, version number 474369

**Comment by bderuijsscher** [comment]
@pgrimaud This issue is generated by design because of the Guzzle client's default to verify all SSL requests. If for some reason the local certificate chain is incorrect, it would be possible to instruct Guzzle to ignore those certificate errors. You might want to consider making this an optional setting in your library as well, such that Guzzle will ignore SSL errors (see http://docs.guzzlephp.org/en/stable/request-options.html#verify)

**Comment by pgrimaud** [comment]
@bderuijsscher thanks for your comment. I’ll take a look at this option.

**Comment by pgrimaud** [comment]
@mejuliver @bderuijsscher 

I guess you use this library like this : 

```php
$cache = new Instagram\Storage\CacheManager(__DIR__ . '/../cache/');

$api = new Instagram\Api($cache);
$api->setUserName('pgrimaud');
```

Guzzle client can be injected as dependency. So you can avoid SSL certificate problem like this : 

```php
$cache = new Instagram\Storage\CacheManager(__DIR__ . '/../cache/');

$client = new \GuzzleHttp\Client([
    'verify' => false
]);

$api = new Instagram\Api($cache, $client);
$api->setUserName('pgrimaud');
```

**Comment by mejuliver** [comment]
its working. thx, thats what im missing, injection on guzzle
