### ISSUE TITLE
This client has not been approved to (truncated...)

### ISSUE THREAD

**Issue by Hardeepcoder** [pgrimaud/instagram-user-feed#35]
can get feed of any other user 
i can show only my feed

**Comment by pgrimaud** [comment]
Hi @Hardeepcoder,

I guess you use the [version ^4.0](https://github.com/pgrimaud/instagram-user-feed#version-40).
If you want to retrieve other user feed, please use the ^5.0 version.

**Comment by Hardeepcoder** [comment]
i tried version 5 but still have error 
Class 'App\Http\Controllers\Instagram\Storage\CacheManager' not found
![screenshot-localhost-8888-2018 10 25-14-02-30](https://user-images.githubusercontent.com/7577119/47486802-cba65080-d85e-11e8-8b8a-d849a75ca704.png)

**Comment by pgrimaud** [comment]
@Hardeepcoder Your line 13 should be : 

```php
$cache = new \Instagram\Storage\CacheManager();
```
and not 
```php
$cache = new Instagram\Storage\CacheManager();
```

**Comment by Hardeepcoder** [comment]
thank you so much its works now
can we get user's feed his/her account is private ?

**Comment by pgrimaud** [comment]
Unfortunately no 😞
