### ISSUE TITLE
Error while getting profile data

### ISSUE THREAD

**Issue by d35k** [pgrimaud/instagram-user-feed#361]
**Version(s) affected**: ^6.16

**Description**  
We started to get error that shown before. I made little investigation and found that some of the nodes are not send or sent empty.

**How to reproduce**  
This problem occurs while fetching the profile data

![Screenshot 2023-12-20 at 20 03 29](https://github.com/pgrimaud/instagram-user-feed/assets/26274293/508ee93d-7ac6-4dfd-a99c-e1d7325562ff)

![image](https://github.com/pgrimaud/instagram-user-feed/assets/26274293/925b8c87-ae5c-47d3-b7cf-709bbaa67b2b)

**Comment by cookieguru** [comment]
Specifically, this line is failing:
https://github.com/pgrimaud/instagram-user-feed/blob/eef6f0b140e5038f178c0c6e18aee01627f2559d/src/Instagram/Hydrator/ProfileHydrator.php#L87

I can confirm that several accounts are missing that property in the `$data` object.  Assuming this change only affects some accounts we'll need some `isset()` calls around it, until the lib can be upgraded to only allow 8.0.0 or higher and we can use the [nullsafe operator](https://www.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.nullsafe)

---

The related function `hydrateMedias()`:
https://github.com/pgrimaud/instagram-user-feed/blob/eef6f0b140e5038f178c0c6e18aee01627f2559d/src/Instagram/Hydrator/ProfileHydrator.php#L73 ...is not failing, but accounts are returning this:
```plain
    [edge_owner_to_timeline_media] => stdClass Object
        (
            [count] => 396
            [page_info] => stdClass Object
                (
                    [has_next_page] => 1
                    [end_cursor] =>
                )

            [edges] => Array
                (
                )

        )
```

So it looks like we're going to need to make more calls to retrieve data

**Comment by cookieguru** [comment]
Click around in the UI and see which actions get the data, and then incorporate those same calls into the library
