### ISSUE TITLE
Undefined property: stdClass::rhx_gis

### ISSUE THREAD

**Issue by danielwaghorn** [pgrimaud/instagram-user-feed#40]
This morning I noticed a few exceptions have occurred on various instances of sites when calling `getFeed()`. It looks as if Instagram may have changed some of the available properties and it's now resulting in an undefined property when the method is called:

```
2019-05-16 11:27:16] production.ERROR: ErrorException: Undefined property: stdClass::$rhx_gis in /home/forge/pura.ae/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlTransportFeed.php:60
Stack trace:
#0 /home/forge/pura.ae/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/home/forge/pur...', 60, Array)
#1 /home/forge/pura.ae/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlTransportFeed.php(60): Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Undefined prope...', '/home/forge/pur...', 60, Array)
#2 /home/forge/pura.ae/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(74): Instagram\Transport\HtmlTransportFeed->fetchData('pura_food', 12)
#3 /home/forge/pura.ae/app/ViewComposers/InstagramComposer.php(37): Instagram\Api->getFeed()
#4 [internal function]: App\ViewComposers\InstagramComposer->compose(Object(Illuminate\View\View))
```

pgrimaud/instagram-user-feed v5.4.1

**Comment by iamsteve** [comment]
If you output $data within src/instagram/Transport/HtmlTransportFeed.php it seems RhxGis is no longer being included within the data returned from instagram. That value is being used as an identifier for caching API calls but is now undefined and throwing an error. We need to identify another value we can use as a cacheable value.

It needs more investigation as to which value would be viable - but for now I've replaced the following:

`
// $newCache->setRhxGis($data->rhx_gis);
$newCache->setRhxGis($data->rollout_hash);
`

However I don't think rollout_hash is the correct value to use so it will result in a larger amount of API calls.

**Comment by rmarsigli** [comment]
> ```
> // $newCache->setRhxGis($data->rhx_gis);
> $newCache->setRhxGis($data->rollout_hash);
> ```

Hello guys, I'm facing the same problem here. At a emergencial fix, @iamsteve solution helped me and made it back to normal, later I'll take a deep look to analyze better. Thank you.

**Comment by pgrimaud** [comment]
Hi, thanks for feedback.

Sorry about the delay...

It seems the `rhx_gis` is no longer mandatory.
I updated the [medias.php](https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/medias.php) in examples to retrieve all my feed and it works pretty well.

Anybody could try this fix : https://github.com/pgrimaud/instagram-user-feed/commit/2c9b1b7c24b5c799e15db0028b6b96e9fef06460 and confirm it?

Then I will release a 5.4.2 version.

Thanks guys

**Comment by aneudysamparo** [comment]
Need to remove rhx_gist from the generator.

**Comment by pgrimaud** [comment]
Please upgrade this dependency with `5.4.2`.

https://github.com/pgrimaud/instagram-user-feed/releases/tag/5.4.2
