### ISSUE TITLE
paginate problem with 403 forbidden

### ISSUE THREAD

**Issue by mycroft84** [pgrimaud/instagram-user-feed#44]
Hi!

I use the latest release and the first paginate page have forbidden (403). The first getFeed is right, but when is set endcursor and get new feed is alredy wrong. The generated url is:

https://www.instagram.com/graphql/query/?query_hash=42323d64886122307be10013ad2dcc44&variables=%7B%22id%22:%224644890951%22,%22first%22:12,%22after%22:%22QVFES0VFNFhRVUpxVGxaWlh2eW9UTmJSQzVocERFZmhxS3p4aXR6MUtTNE5ibUdiQmV5eHh5UlZHRnFMc2plVDh2RWM0VHdobVgwQ2FhYkotb0ZEZGR3Wg==%22%7D

**Comment by mycroft84** [comment]
My code...

$cache = new Instagram\Storage\CacheManager(APPPATH.DIRECTORY_SEPARATOR.'cache'.DIRECTORY_SEPARATOR);
$api   = new Instagram\Api($cache);
 $api->setUserName('...');
 $feed = $api->getFeed();

....

if ($feed->getEndCursor()) {
                $endCursor = $feed->getEndCursor();
                $api->setEndCursor($endCursor);
                $feed = $api->getFeed();

                ....
            }

**Comment by gordienko** [comment]
Most likely the problem is associated with changes to Instagram.

https://github.com/rarcega/instagram-scraper/issues/424
https://github.com/instabot-py/instabot.py/issues/2347

**Comment by pgrimaud** [comment]
I just fixed it with : https://github.com/pgrimaud/instagram-user-feed/commit/9fe65b5abe141111d70318c77df3983f128520f4

Please update to 5.5.2 : https://github.com/pgrimaud/instagram-user-feed/releases/tag/5.5.2

**Comment by gordienko** [comment]
Excellent thank you!
