### ISSUE TITLE
Error with $ProfilePage

### ISSUE THREAD

**Issue by randinfo** [pgrimaud/instagram-user-feed#46]
Hi, it seems that instagram changed there api, no ?

(ErrorException(code: 0): Undefined property: stdClass::$ProfilePage at /var/www/default/htdocs/vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlTransportFeed.php:68)

**Comment by pgrimaud** [comment]
Hi @randinfo 

Same question in https://github.com/pgrimaud/instagram-user-feed/issues/45 : Are you on shared server for your hosting?

**Comment by randinfo** [comment]
No i use a private server, but i've found a workaround, i think it's an instagram limitation, i've modified your code to add proxy handling and now it works fine. I'm using 10 proxys to make 60 requests/min

I think that instagram added an agressive anti-abuse system.

**Comment by pareshsojitra** [comment]
> 
> 
> No i use a private server, but i've found a workaround, i think it's an instagram limitation, i've modified your code to add proxy handling and now it works fine. I'm using 10 proxys to make 60 requests/min
> 
> I think that instagram added an agressive anti-abuse system.
Yes that's right, Can you share the updated code with proxys ?
