### ISSUE TITLE
Was working, now its not

### ISSUE THREAD

**Issue by kromalski** [pgrimaud/instagram-user-feed#47]
Hello,
Everything was working fine but suddenly stopped. Nothing was changed. What can be the issue?
Got error:
Warning: Invalid argument supplied for foreach() in ...Instagram/Hydrator/HtmlHydrator.php on line 33

**Comment by thomashausheer** [comment]
Hi,
I can confirm the same issue. strange is, on some servers it still works fine (different shared hostings with same configuration/provider).

**Comment by matthiggins** [comment]
I'm on a private server and i'm getting issues as well.  Just started today for me.

**Comment by pgrimaud** [comment]
Do you have any estimation about the number of requests to Instagram you made by day?

**Comment by thomashausheer** [comment]
not many, max 100 per day

**Comment by kromalski** [comment]
Max 10-50 here

**Comment by pgrimaud** [comment]
I can't reproduce it on my side...

I just tried to forward x-csrf-token https://github.com/pgrimaud/instagram-user-feed/commit/28e124f18671a8f888c3266bafeb5dc815a93a6b, maybe it will fix it.

Some one with error could try version 5.5.3 ? https://github.com/pgrimaud/instagram-user-feed/releases/tag/5.5.3

Thanks

**Comment by thomashausheer** [comment]
thnks, tried with the version 5.5.3 - on some shared servers it works, on some not. it shows always "Warning: Invalid argument supplied for foreach() in /home/httpd/vhosts/.../httpdocs/assets/dev/vendor/pgrimaud/instagram-user-feed/src/Instagram/Hydrator/HtmlHydrator.php on line 33"

**Comment by pgrimaud** [comment]
Yeah! Finally got the error! I'm working to find a fix. 😄

**Comment by pgrimaud** [comment]
After tests, here is the problem : 

**Instagram blocks your ip after too many calls. Then you have to be logged to an Instagram account to access to a public profil.**

The only workaround is to simulate a connection on this dependency with real credentials.

**Comment by thomashausheer** [comment]
so this means, this script doesn't work on shared hosting servers anymore, right?

**Comment by matthiggins** [comment]
Any idea on how to simulate an authenticated request from the server?

**Comment by pgrimaud** [comment]
@thomashausheer With login process, it should work

@matthiggins Yes it's possible, I'm working on it.

**Comment by matthiggins** [comment]
@pgrimaud what do you mean by with the login process?  Is there a way to programmatically authenticate through this package?

Thanks for all of the hard work. I wonder if Instagram is cracking down on web scraping services by rate limiting requests. Looks like even if you change your IP it will only work for a certain amount of time and then get blocked again.

Works just fine on my local and staging environments. Doesn’t work in production anymore. I’m not on a shared server.

Cheers!

**Comment by pgrimaud** [comment]
I just released a dirty "beta" version with login process : 

`composer req pgrimaud/instagram-user-feed "5.6-beta"`

Actually, there is no BC, but the code is a little bit dirty...

You can take a look at examples files `getProfileWithLogin.php` and `getMediasWithLogin.php`.
You just have to change login / password data.

Someone can try it? If this release fix issues, I will release a v6.0.0 with better code and probably some little BC.

Please open another issue to talk about it. Thanks.

**Comment by asylwan** [comment]
> I just released a dirty "beta" version with login process :
> 
> `composer req pgrimaud/instagram-user-feed "5.6-beta"`
> 
> Actually, there is no BC, but the code is a little bit dirty...
> 
> You can take a look at examples files `getProfileWithLogin.php` and `getMediasWithLogin.php`.
> You just have to change login / password data.
> 
> Someone can try it? If this release fix issues, I will release a v6.0.0 with better code and probably some little BC.
> 
> Please open another issue to talk about it. Thanks.

Excellent, I can confirm that this is working. Thanks a lot for your help.

**Comment by thomascheper** [comment]
I also have the same issue: code works fine at one Server, but at localhost and a website on another server it doesn't work anymore. Error(Warning: Invalid argument supplied for foreach() in ...Instagram/Hydrator/HtmlHydrator.php on line 33)

After updating to localhost to 5.6 i've got this issue: 
Fatal error: Uncaught exception 'Instagram\Exception\InstagramAuthException' with message 'Instagram blocked your IP.  
in
/instagram-user-feed/src/Instagram/Transport/HtmlTransportFeed.php on line 73

**Comment by pgrimaud** [comment]
@thomascheper Take a look at this example : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getMediasWithLogin.php 👍

**Comment by thomascheper** [comment]
Saw it, Thank you! And it works too!

**Comment by thomascheper** [comment]
@pgrimaud  One question: when someone visit my page, this code wil login me every single time. Is there a possibility to get a return value and "store" the login values/token/.. so that i do not log in every single time? 
Also i load images within an ajax call, that isn't possible anymore because after one call Instagram refuse to login again.

**Comment by pgrimaud** [comment]
@thomascheper I will add "reusing of auth token" in the next clean release (6.0.0).
By then, you can store in cache (Redis or filesystem) data fetched from Instagram feed.

**Comment by sezginriggs** [comment]
Hello @pgrimaud when do you plan to release v6.0.0? "reusing of auth token" would be very nice.
