### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mdagostino** [pgrimaud/instagram-user-feed#5]
With the new update ( 3.0 ) this error still not fixed. Maybe needs more parameters in to the cookie.

**Comment by jannejava** [comment]
Have the same error. You are using GraphQL which is not the endpoint this package uses. Seems like this endpoint is dead: https://www.instagram.com/<username>/?__a=1 :-(

**Comment by jannejava** [comment]
It seems like we are not alone in this:
https://github.com/postaddictme/instagram-php-scraper/issues/336

And the fix with hardcoding in a cookie does seem a bit fragile. Hm... 
https://github.com/postaddictme/instagram-php-scraper/pull/335

**Comment by pgrimaud** [comment]
I'm gonna try to generate a cookie with login / password.

Something like this : 

```php
$api = new Api();

// for media, userId is mandatory!
$api->setUserId(184263228);
$api->setLogin('pgrimaud');
$api->setPassword('password123');

$api->retrieveMediaData(true);

$feed = $api->getFeed();
```

What do you think about it? @jannejava @mdagostino

**Comment by mdagostino** [comment]
Now this link works

https://www.instagram.com/graphql/query/?query_hash=472f257a40c653c64c666ce877d59d2b&variables={"id":"1368353436","first":12}

**Comment by pgrimaud** [comment]
@mdagostino holy shit... until when?

**Comment by jannejava** [comment]
Could be hard to get it to work over time. If the cookie could work to 2020 I would be happy. ;-)

https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/

> The following will be available until early 2020:
> 
> Basic - to read a user’s profile info and media

**Comment by mdagostino** [comment]
The link is broken again, may be we need to find another work around.

**Comment by joshbmarshall** [comment]
I wonder if we can use the same logic that http://instafeedjs.com/ does. It uses an access token. e.g. it creates a url like https://api.instagram.com/v1/users/5467372861/media/recent?access_token=5467372861.1677ed0.8bd9ec9b2d4d48a8b36dc891edcadcf3 - that url works for me with curl on cli ? It does mean you have to authenticate to get a token but is once-only

**Comment by pgrimaud** [comment]
Many thanks @jannejava 

I fixed all tests and the release [4.0.0](https://github.com/pgrimaud/instagram-user-feed/releases/tag/4.0.0) is now working.

`Seems like you can only access your own media until 2020 other user's media December 11, 2018`

We must find any solution to use the new Instagram API (graphQL) before end of the year.

**Comment by cookieguru** [comment]
Instagram's Graph API requires:
* A Facebook Page
* An Instagram _Business_ Account
* Facebook Login (OAuth)
* An app submission to Facebook showing how the Instagram API will be used
* Approval for said app

I haven't looked in to the T&C but programmatic access for displaying content on another website is probably not going to lead to approval, and all of that seems to be out of scope for this package anyways.

**Comment by pgrimaud** [comment]
@cookieguru Yeah, It's a pain in the ass. 
I will probably simulate a login process with login and password. Then fetch data with cookie generated with credentials.

**Comment by prince-code** [comment]
I have the same problem when I try to get followers

**Comment by pgrimaud** [comment]
@prince-code Which version do you use?
