### ISSUE TITLE
Paginate in Version 4

### ISSUE THREAD

**Issue by inurear** [pgrimaud/instagram-user-feed#51]
Currently the documentation is written as:

```
// First call :

$api = new Api();
$api->setUserId(184263228);
$api->setAccessToken('1234578.abcabc.abcabcabcabcabcabcabcabcabcabc');

$feed = $api->getFeed();

$endCursor = $feed->getMaxId();

// Second call : 

$api = new Api();
$api->setUserId(184263228);
$api->setAccessToken('1234578.abcabc.abcabcabcabcabcabcabcabcabcabc');
$api->setMaxId('1230468487398454311_184263228');

$feed = $api->getFeed();

// And etc...
```

I was wondering if it should read:

`$api->setMaxId($endCursor);`

and if so, why am I not able to pull more content? ... or ... why am I mistaken?
I'm not certain to the purpose of MaxId, if you can shed some light on what purpose it serves.

Thanks!

**Comment by pgrimaud** [comment]
Version ^4.0 is no more supported.
