### ISSUE TITLE
Feed stopped loading - not logged in

### ISSUE THREAD

**Issue by neonovic** [pgrimaud/instagram-user-feed#52]
Few months before the getFeed() stopped loading the feed. When I debug what Guzzle returns as a html page - it returns the "Login" page, without showing the "username" content. The "fetchData" in HtmlTransportFeed cannot preg_match the <script> code properly, because it's not there.

Interesting is, on my localhost it still works properly. Only server versions stopped fetching the feed correctly.

**Comment by pgrimaud** [comment]
Hi @neonovic which version do you use? 

On ^5.0, you often have to login to paginate on feed.

You can see an example here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getMediasWithLogin.php

**Comment by neonovic** [comment]
I am using no pagination, just simply fetching images from a useraccount. Simply by:
`$api = new Api();
$api->setUserName($username);
$feed = $api->getFeed();`

I was using 5.4 and everything worked fine. But few months ago it stopped working. When I debug $html in HtmlTransportFeed in fetchData, I can see that it's not fetching the user` instagram page. But only the general "Login" version of the page.

I don't know why. The exact same code on my localhost does still work properly.

**Comment by pgrimaud** [comment]
Yeah, this is a known bug : https://github.com/pgrimaud/instagram-user-feed/issues/45 or https://github.com/pgrimaud/instagram-user-feed/issues/47.

Please upgrade to 5.6-beta : https://github.com/pgrimaud/instagram-user-feed/releases/tag/5.6-beta

I will release a 6.0 version soon with a better login handling.

**Comment by neonovic** [comment]
Thank you. Ok, now I see the exception message "Instagram blocked your IP. Login is required."

Just to be sure. If my code is without any login, now I have to update my code for a logging in?

**Comment by pgrimaud** [comment]
Yes, you have to update your code. 

You can fin an example here :  https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/getMediasWithLogin.php

You just have to add :

```php
$api->login('username', 'password');
```

**Comment by neonovic** [comment]
Thank you, I have added login, then I had to add the Cache. But still getting this error:

`Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `400 Bad Request` response:
{"message": "checkpoint_required", "checkpoint_url": "/challenge/8189442180/huQvMkCaei/", "lock": false, "status"`

**Comment by neonovic** [comment]
I have visited my instagram in browser. It asked me to validate the login activity from the "shared hosting" place. Even after confirming and refreshing the webpage, it still asks me again and again to confirm. It doesn't allow me to access the Instagram from a webpage code.

**Comment by neonovic** [comment]
Ok, I have created a brand new fake email, new Instagram account in an anonymous window and it works. Now I will not login to this account anymore from my browser :)

**Comment by pgrimaud** [comment]
Yes, the best way is to created a dummy instagram account for this dependency.

So, it works for you?

**Comment by neonovic** [comment]
Yes, everything works now. Thanks a lot!
