### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by samuelhgf** [pgrimaud/instagram-user-feed#57]
Undefined property: stdClass::$ProfilePage in ../vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlTransportFeed.php on line 69

**Comment by pgrimaud** [comment]
Hi, which version?

**Comment by samuelhgf** [comment]
5.0

**Comment by pgrimaud** [comment]
Could you try with 5.6-beta with login process. 

You can find an example in the repository.

**Comment by samuelhgf** [comment]
I will. But I would like to not use login. Because this Api will be used by my clients. So do not want to ask then to create a acess token in their Instagram.

**Comment by timohausmann** [comment]
I'm having the same issue (Undefined property $ProfilePage) with 5.0 on a server with php 7.2.28. Weirdly, it works in two different environments (php 7.0.33 and 7.2.4).  Any system requirements we should be aware of?

I just tried 5.6-beta. `getProfile.php` works, `getMedia.php` returns profile info but no media. The `WithLogin.php`-Examples with my credentials give this error:

> Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `400 Bad Request` response: {"message": "checkpoint_required", "checkpoint_url": "/challenge/9185323428/gsY3lASZ05/", "lock": false, "status": "fail (truncated...)

**Comment by pgrimaud** [comment]
Hello, I released a new version (6.0). Could you upgrade to this one?
