### ISSUE TITLE
Pixel Union token generator shutdown for v4.0

### ISSUE THREAD

**Issue by EHLOVader** [pgrimaud/instagram-user-feed#59]
I think that v4.0 is no longer going to be viable. Pixel union reports that their token generator and instagram feeds in themes are no longer supported https://support.pixelunion.net/hc/en-us/articles/360041460554-Important-notice-Instagram-feed-removal

The reason I was using it was because scraping was being blocked. Is that also true still? or is v5.0 working still?

**Comment by pgrimaud** [comment]
Thanks, I just updated the documentation.
