### ISSUE TITLE
Trying to get property 'sessionName' of non-object

### ISSUE THREAD

**Issue by volkv** [pgrimaud/instagram-user-feed#60]
If you run API without `optional` Cache instance...

**Comment by volkv** [comment]
I mean your code from `Readme` isn't working
![image](https://user-images.githubusercontent.com/14368228/77820029-53e1f280-70f0-11ea-9bc3-f50633d52357.png)
as well as using Api without CacheManager

**Comment by thierrymaasdam** [comment]
Same error here.

**Comment by pgrimaud** [comment]
I created a new version (5.6.1) with the PR of @ikiselev1989

Thanks
