### ISSUE TITLE
Set App ID, Client and Secret...

### ISSUE THREAD

**Issue by ezequiel9** [pgrimaud/instagram-user-feed#62]
I don't understand one thing... the new Instagram requires an App, then get an access token, then user id to be able to connect to the api.. I am totally wrong? how did you make this? The documentation is so big and confused. sorry

**Comment by rjbathgate** [comment]
This is a web scraper, rather than API integration. As per repo description: _Easily fetch your or any Instagram feed without OAuth for PHP_

**Comment by ezequiel9** [comment]
Yeah I got it, thanks
