### ISSUE TITLE
Instagram blocked your IP. Login is required.

### ISSUE THREAD

**Issue by danielchodusov** [pgrimaud/instagram-user-feed#63]
Hello,

I have start receiving this error "Instagram blocked your IP. Login is required." when calling getFeed. Is there any way how to get rid of the message?

**Comment by flyalperen** [comment]
Hi,
You will get this error when you catch rate limit on Instagram. Slow down
request while using the API. Or log in and run one with Instagram account.

<notifications@github.com> şunu yazdı:

**Comment by danielchodusov** [comment]
Ah, I thought the are a limit in Instagram\Storage\CacheManager .. so I have to implement a rate limit myself right?

**Comment by flyalperen** [comment]
Yes you should. Or you can solve this problem by logging in with multiple Instagram accounts.

Example:
```
<?php

require __DIR__ . '/../vendor/autoload.php';
	$usernames = array('username1','username2','username3','username4'); // Usernames
	$usernamex = $usernames[$random]; 
    $passwordx = "yourpassword"; // Password (The password on all accounts must be the same.)
    $random = rand(0,3);//

try {
    $cache = new Instagram\Storage\CacheManager(__DIR__ . '/../cache/');
    $api = new Instagram\Api($cache);
    $api->login($usernamex,$passwordx,0);
    $api->setUserName('pgrimaud');

    // only the first page
    /** @var \Instagram\Hydrator\Component\Feed $feed */
    $feed = $api->getFeed();

    echo '============================' . "\n";
    echo 'User Informations : ' . "\n";
    echo '============================' . "\n\n";

    echo 'ID               : ' . $feed->getId() . "\n";
    echo 'Full Name        : ' . $feed->getFullName() . "\n";
    echo 'UserName         : ' . $feed->getUserName() . "\n";
    echo 'Following        : ' . $feed->getFollowing() . "\n";
    echo 'Followers        : ' . $feed->getFollowers() . "\n";
    echo 'Biography        : ' . $feed->getBiography() . "\n";
    echo 'External Url     : ' . $feed->getExternalUrl() . "\n";
    echo 'Profile Picture  : ' . $feed->getProfilePicture() . "\n";
    echo 'Verified Account : ' . ($feed->isVerified() ? 'Yes' : 'No') . "\n";
    echo 'Private Account  : ' . ($feed->isPrivate() ? 'Yes' : 'No') . "\n";
    echo 'Media Count      : ' . $feed->getMediaCount() . "\n\n";

} catch (Exception $exception) {
    print_r($exception->getMessage());
} catch (\GuzzleHttp\Exception\GuzzleException $e) {
    print_r($exception->getMessage());
}
?>
```

**Comment by pgrimaud** [comment]
@flyalperen gives the right answer! 😄

**Comment by flyalperen** [comment]
The problem can be solved with the codes I gave above. That's the right answer! :laughing:

**Comment by sz3jdii** [comment]
Is this ban temporary or permanent?

**Comment by flyalperen** [comment]
> Is this ban temporary or permanent?
It's a temporary ban. I don't know the limit exactly, but  has an hourly limit on your server IP.

**Comment by pgrimaud** [comment]
Depend of hosting you used : 
  - Dedicated hosting 
    - Sometimes a permanent ban
    - Often a temporary ban
  - Shared hosting
    - Often/always a permanent ban

**Comment by sz3jdii** [comment]
Thanks :)

**Comment by pgrimaud** [comment]
Hello, I released a new version (6.0). Could you upgrade to this one?

**Comment by vietel** [comment]
@flyalperen  @pgrimaud pgrimaud How can I use proxies in combination with your code in the _credentials.php_ file (**examples** folder)

Thank you so much !

**Comment by pgrimaud** [comment]
@vietel Could you create a new issue, and I will show you an example. Thanks
