### ISSUE TITLE
 Client error: 'POST https://www.instagram.com/accounts/login/ajax/' 

### ISSUE THREAD

**Issue by coolskin2b** [pgrimaud/instagram-user-feed#65]
Hello,

I just realized that I can no longer connect to Instagram.

I have this error message:

Uncaught GuzzleHttp \ Exception \ ClientException: Client error: 'POST https://www.instagram.com/accounts/login/ajax/' resulted in a '400 Bad Request' response:
Bad request
in ... vendor / guzzlehttp / guzzle / src / Exception / RequestException.php: 113.
until yesterday it worked.

Do you have the same problem?

cordially

**Comment by pgrimaud** [comment]
Hello @coolskin2b 

Yes, Instagram changed his login process. I'm working on a hotfix.

**Comment by pgrimaud** [comment]
Password encryption changed : https://github.com/unoemon/instagram-enc_passowrd-generator/blob/master/enc_passowrd-generator.js

**Comment by rephlex187** [comment]
Got the same issue, how does Instagram encrypt the password using Username/Password only?

**Comment by pgrimaud** [comment]
It's a AES 256 GCM encryption. I found a solution in JavaScript here : https://pastebin.com/raw/nYL2W2bG

But I have trouble to implement it on PHP.

**Comment by rephlex187** [comment]
Got it working without node-webcrypto-ossl since it requires native modules, let me try PHP

**Comment by pgrimaud** [comment]
@rephlex187 Did you succeeded with PHP?

**Comment by pgrimaud** [comment]
I fixed it with this workaround : https://github.com/pgrimaud/instagram-user-feed/commit/96ad4cf54d1ad331b337f325c73e664999a6d066

**Comment by pgrimaud** [comment]
Please upgrade to 5.6.2 : https://github.com/pgrimaud/instagram-user-feed/releases/tag/5.6.2 😄

**Comment by LudovicFauchet** [comment]
Hello,
For me the hotfix doesn't work :(

`: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `400 Bad Request` response: {"message": "checkpoint_required", "checkpoint_url": "/challenge/2471176/CfHcIxPw0D/", "lock": false, "status": "fail"}
`

**Comment by pgrimaud** [comment]
Hello @LudovicFauchet 

The hotfix is working 😄 

**This is another problem**, the 2FA authentication. (You can see the "checkpoint_required, on the Instagram response. It means : the login is working, but you must provide a manual action to confirm login).

I'm actually working on a new login authentication process, it should be release at the end of the week.

**Comment by LudovicFauchet** [comment]
@pgrimaud 

Ok but it's tell me everytime i call the api on my server. I use the login way because it's say my server api is ban ^^

Cheers
