### ISSUE TITLE
GuzzleHttp\Exception\ClientException - Response 429

### ISSUE THREAD

**Issue by thivalle** [pgrimaud/instagram-user-feed#67]
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.instagram.com/bigbangdigital/` resulted in a `429 -` response:
<!DOCTYPE html>
<html lang="en" class="no-js logged-in ">
    <head>
        <meta charset="utf-8">
        <meta http-e (truncated...)
 in /var/www/html/libs/instagram_no_token/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/html/libs/instagram_no_token/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create()
#1 /var/www/html/libs/instagram_no_token/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /var/www/html/libs/instagram_no_token/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler()
#3 /var/www/html/libs/instagram_no_token/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/libs/instagram_no_token/vendor/guzzlehttp/promises/src/ in /var/www/html/libs/instagram_no_token/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
root@appserver1n:/var/www/html/libs/instagram_wd#

**Comment by pgrimaud** [comment]
Hello @thivalle,

Which version are you using?

Your IP has been soft banned. You should make less queries or use proxies.

**Comment by thivalle** [comment]
I am using a new version 6.
On successful login to Chrome, I believe that my ip is not blocked.
I also tried on 2 servers with different ips.

I admire his work and am extremely dependent on him.

**Comment by pgrimaud** [comment]
How many requests did you get in the last hour?

What do you fetch exactly? Only one profile? With medias?

**Comment by thivalle** [comment]
I have an ecoomerce platform in Brazil. My clients register Instagram to display the latest posts in their stores. I have about 200 customers.

I created a new server and after a while it crashed again. It really is the question of the request quantity, even if I put a 10 second sleep.
I also use a media cache that expires every 3 hours, so I don't make the request every time.

Can you refer me to a proxy service?

thank you

**Comment by pgrimaud** [comment]
Are you fetching data with the same instagram account?

I'm using https://proxy6.net/ for various projects.

**Comment by Himanshu096singh** [comment]
**How to solve:** Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://www.instagram.com/p/xxxxxxxx/?__a=1&__d=dis` resulted in a `401 Unauthorized` response:
