### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by LudovicFauchet** [pgrimaud/instagram-user-feed#68]
Hello,

I migrate to the new version 6.1.0, but i always have the same error :'( 
```
Fatal error
: Uncaught Instagram\Exception\InstagramAuthException: Unknown error (Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `400 Bad Request` response: {"message": "checkpoint_required", "checkpoint_url": "/challenge/2471176/HOBb2vrI7s/", "lock": false, "status": "fail"} ).
```

Does i've done a bad things ? i used your exemple in the readme.

Cheers

**Comment by pgrimaud** [comment]
Hello @LudovicFauchet 

Can you try with a new Instagram Account? (a dummy one)

**Comment by LudovicFauchet** [comment]
@pgrimaud ,

Do you want to say a new empty account ? 
The account use to login method can be the same used to getProfile ?

Cheers

Many thanks for your reactivity

**Comment by pgrimaud** [comment]
> Do you want to say a new empty account ?

Yes. I'm working for a workaround to bypass **the checkpoint challenge**.

> The account use to login method can be the same used to getProfile ?

You just have to login one time. The session data will be set in cache and used each time to get a profile, medias or stories.

**Comment by LudovicFauchet** [comment]
With the new empty account it seems to work but now i can't access to the medias of my other profile with this account.

```
Fatal error
: Uncaught Error: Cannot access private property Instagram\Model\Profile::$medias
```

**Comment by pgrimaud** [comment]
Weird.

Could you paste your code?

**Comment by LudovicFauchet** [comment]
@pgrimaud 

It's ok for me it's work, i badly used the getMedias Method.

Cheers

Thanks for your help
