### ISSUE TITLE
Why can not we get a specific media data by code or url ?

### ISSUE THREAD

**Issue by btworld-tr** [pgrimaud/instagram-user-feed#71]
Hello @pgrimaud 
I think your api is not working with media code or url for a specific post data. Is it impossible ?

**Comment by pgrimaud** [comment]
Hello @btworld-tr 

You want to fetch data from a specific post? (comments, etc.)

**Comment by btworld-tr** [comment]
Hello again,
Yes you are right. I am looking for getting a media post data like image caption type etc. 
https://www.instagram.com/p/CAG3E8-A3wf/?__a=1 like that

**Comment by pgrimaud** [comment]
Good idea, I will add this feature!

**Comment by btworld-tr** [comment]
> Good idea, I will add this feature!

Also remember please, media types can be image, video and sidecar. 
Sidecars are including videos and images at the same time or only images or only videos.
Thanks!

**Comment by pgrimaud** [comment]
> Also remember please, media types can be image, video and sidecar.

Thanks for the reminder. Can you give me an example of post with this one?

**Comment by btworld-tr** [comment]
> > Also remember please, media types can be image, video and sidecar.
> 
> Thanks for the reminder. Can you give me an example of post with this one?

Sidecars are like a carousel.
Please, look at this one :
https://www.instagram.com/p/CAp5BPPpewj/?__a=1
and includes videos and their poster images
type : GraphSidecar
Look at the GraphVideo node and it has got video_urls for each one

An other post: https://www.instagram.com/p/CAnqPB-Jzcj/?__a=1
And this type is sidecar, too and it has got only images.

Sometimes they have got both (image and video) in a post type of sidecar

**Comment by pgrimaud** [comment]
Hello, I just released new version 6.2.0.

You can now fetch uniq media. 
Here's an example : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/media-detailed.php

Feedback is appreciated 😃

**Comment by btworld-tr** [comment]
> Hello, I just released new version 6.2.0.
> 
> You can now fetch uniq media.
> Here's an example : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/media-detailed.php
> 
> Feedback is appreciated 😃

Wow. That's amazing. Be sure, I will check it and if i find any issue, I will inform here.
Thanks!
