### ISSUE TITLE
Get More Media Using Cursor

### ISSUE THREAD

**Issue by Pezhvak** [pgrimaud/instagram-user-feed#72]
Hey, in previous version we could fetch more medias using cursor, this is now gone sadly,
what we have instead is getMoreMedia which takes profile as the input which is not efficient,
let me demonstrate, my app gets the profile for the first http request, all fine, now i do not want to show more than the first 12 posts, only if needed i want to load another 12 posts, this is where the problem starts, i should either fetch all the posts or only the first 12. i cannot load more on demand, simply because http is stateless and i cant load more using the cursor. imagine a user has 300 posts, and all of them should get loaded for no reason.

btw, awesome repo, thanks for your efforts.

ps: it would be awesome to add toArray() method on the objects so we can pass it to the response right away

**Comment by Pezhvak** [comment]
i don't know how you would like to address the first issue, but for converting objects into array and also serialization support i created a pull request, please visit #73

**Comment by pgrimaud** [comment]
Hello @Pezhvak,

First, thanks for your PR #73 

If you take this example : 
```PHP
$api = new Api($cachePool);
$api->login('username', 'password');

$profile = $api->getProfile('robertdowneyjr');

print_r($profile->getEndCursor());
```

Endcursor is available as before, but automatically used in `getMoreMedias` method.

If I had a second parameter to the method `getMoreMedias` like this :

```php
$profile = $api->getMoreMedias($profile, $endCursor);
```

It could match to your need?

**Comment by Pezhvak** [comment]
@pgrimaud yes, this would be perfect 👌

**Comment by pgrimaud** [comment]
I guess we could avoid this useless request if you know the user_id.

Like that : 

```php
$api = new Api($cachePool);
$api->login($credentials->getLogin(), $credentials->getPassword());

$profile = new Profile();
$profile->setId(12345678); // set your userId here

$profile = $api->getMoreMedias($profile);
```

**Comment by Pezhvak** [comment]
in that case we can even use $profile->setEndCursor(); and no change in the code. but it might not be the best looking solution for this. i will use this solution for now

**Comment by pgrimaud** [comment]
What could be the best solution?
Add more parameters to `getMoreMedias()` (userId & endCursor) to avoid breaking changes?

**Comment by Pezhvak** [comment]
since both of them are required to load more, we have three approaches:
1- add a new method, instead of using the existing one like `getMoreMediasWithCursor($userId, $endCursor)`
2- make a second optional parameter for `getMoreMedias` which receives a new object, like new `LoadMoreCursor($userId, $endCursor)`
3- add two more optional parameters to `getMoreMedias` and verify them both if one exists and another is not given and throw an error to make developer aware endCursor is not enough and user_id is needed or visa-versa.

however personally it think the first approach is the cleanest one. and more developer friendly. what's your opinion?

**Comment by pgrimaud** [comment]
First approach is the best developer friendly. You're right, no need to complexified methods. 👍 

I push this : https://github.com/pgrimaud/instagram-user-feed/commit/53666442821903a0b332b1a4213e7118ac6dfc45

And an example here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/medias-endcursor.php

**Comment by Pezhvak** [comment]
well done, thank you @pgrimaud fast and neat 👌

**Comment by pgrimaud** [comment]
I will develop this feature (https://github.com/pgrimaud/instagram-user-feed/issues/71) then publish a new release with this changes, probably 6.2.0.

**Comment by Pezhvak** [comment]
awesome 👍 let me know if i could be any help, i leaved a commend on the 53666442821903a0b332b1a4213e7118ac6dfc45 if you where interested to further enhance the code.

**Comment by pgrimaud** [comment]
Sure, I fixed it : https://github.com/pgrimaud/instagram-user-feed/commit/5b8f9a7c492dc10fafa239cd493372e2586129e9

Thanks again 👍
