### ISSUE TITLE
symfony/cache 4 compatibilty

### ISSUE THREAD

**Issue by a4chris** [pgrimaud/instagram-user-feed#74]
I'm using Pimcore6. It relies on Symfony 4. Is there a way using the new version 6 with symfony/cache 4 ? I need the new login capabilities.

**Comment by pgrimaud** [comment]
Hi @a4chris 

This package is shipped with symfony/cache: "^5.0". I may update this constraint to also allow symfony/cache: "^4.4".

What do you think about it?

**Comment by a4chris** [comment]
That would be very nice. Pimcore7 with Symfony 5 will be launched in Fall this Year. Can't wait for that.
A great package. I'm using it a couple of Years. Thanks a lot.
But now with package Version 5 @zuck is blocking our Server IP. :(

**Comment by pgrimaud** [comment]
I added new constraint about cache : https://github.com/pgrimaud/instagram-user-feed/commit/67ce2a356e64ad1ef731da7c9168de68e391216b and release version 6.2.1.

Could you try to update this dependency on your Pimecore6 project?

**Comment by a4chris** [comment]
it worked like a charm! Thank You so much!

**Comment by pgrimaud** [comment]
Perfect 😄

**Comment by tonyellow** [comment]
I have the same problem:
Using version ^6.2 for pgrimaud/instagram-user-feed
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pgrimaud/instagram-user-feed 6.2.2 requires symfony/cache ^3.4|^4.4|^5.0 -> no matching package found.
    - pgrimaud/instagram-user-feed 6.2.1 requires symfony/cache ^4.4|^5.0 -> no matching package found.
    - pgrimaud/instagram-user-feed 6.2.0 requires symfony/cache ^5.0 -> no matching package found.
    - Installation request for pgrimaud/instagram-user-feed ^6.2 -> satisfiable by pgrimaud/instagram-user-feed[6.2.0, 6.2.1, 6.2.2].

I have symfony/cache version v4.3.11.
What can I do to solve?
