### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by KeesCornelisseEF2** [pgrimaud/instagram-user-feed#75]
I'm using Drupal 8 which require Symfony 3.4. Is it possible to downgrade the require version of the symfony/cache package? I hope you can help me :-)

**Comment by pgrimaud** [comment]
I added new constraint to allow symfony/cache:^3.4 (version 6.2.2).

Could you try to install this dependency on your Drupal 8 project and test it?

Thanks 🙏

**Comment by KeesCornelisseEF2** [comment]
Thanks for reply so fast! I can test it, but composer cannot find 6.2.2. Maybe its not published by Packagist?

**Comment by pgrimaud** [comment]
Damn, this version wasn't automatically published on packagist.

I manually forced update directly on packagist, could you try again?

**Comment by KeesCornelisseEF2** [comment]
The update was succesfully, but the main error was the same as before. I see this Instagram error, but inside Instagram there is no option to allow this.

**Comment by pgrimaud** [comment]
Alright, this is a "temporary" problem. 

I'm working for a fix here : https://github.com/pgrimaud/instagram-user-feed/issues/69

Gonna release it soon 🤞

**Comment by KeesCornelisseEF2** [comment]
Okay, thank you, when do you expect to have it ready?

**Comment by pgrimaud** [comment]
No ETA yet, depending on my free time.
End of this week I guess, or start of the next week.

**Comment by KeesCornelisseEF2** [comment]
Okay, thanks for reply!

**Comment by JorgeosorioDev** [comment]
Hello, thanks for you amazin code.
This is only for Symfony?

Because i have this error in LOCAL with xampp:
 Fatal error: Uncaught Error: Class 'FilesystemAdapter' not found in C:\xampp\htdocs\user-feed\index.php:5 Stack trace: #0 {main} thrown in C:\xampp\htdocs\user-feed\index.php on line 5

Thanks.

**Comment by pgrimaud** [comment]
Hi @JorgeosorioDev 

This package is for all PHP projects.
If you have any problem with installation, you could you create your own issue?

Thanks 🙏
