### ISSUE TITLE
Typo in Pagination Example - getMedias should be getMedias()

### ISSUE THREAD

**Issue by a4chris** [pgrimaud/instagram-user-feed#76]
<?php

$api = new Api($cachePool);
$api->login($credentials->getLogin(), $credentials->getPassword());

$profile = $api->getProfile('twhiddleston');

//print_r($profile->getMedias); // 12 first medias
print_r($profile->getMedias()); // 12 first medias

do {
    $profile = $api->getMoreMedias($profile);
    //print_r($profile->getMedias); // 12 more medias
    print_r($profile->getMedias()); // 12 more medias

    // avoid 429 Rate limit from Instagram
    sleep(1);
} while ($profile->hasMoreMedias());

**Comment by pgrimaud** [comment]
Nice catch! Could you submit a PR to fixed it?

Thanks 🙏

**Comment by a4chris** [comment]
Don't know how to link a pull requests. Sorry

**Comment by pgrimaud** [comment]
No worries. I fixed this typo.

Thanks for reporting 😄
