### ISSUE TITLE
Strange Problem with getMoreMedias

### ISSUE THREAD

**Issue by xsindesign** [pgrimaud/instagram-user-feed#78]
I have an odd problem when I call getMoreMedias($profile) (just once) on a prod server my response body from fetchJsonDataFeed() is {"data":{"user":null},"status":"ok"} which of course throws a PHP error afterward.
I think everything is ok in my code since it works on a test server, I'm getting the right response and getting the "more medias". Also on the prod server I can get the "first part" of the medias and the profile fine.

**Comment by pgrimaud** [comment]
Hi @xsindesign 

So the complete data sent by Instagram is only {"data":{"user":null},"status":"ok"}?
Which user are trying to fetch? 
Is your cache driver functional?

**Comment by xsindesign** [comment]
Hi @pgrimaud !
I tested again with 6.3 and I have the same problem.
Yes that's the response data I get on the getMoreMedias call, but getMedias is working fine.
Cache is working fine.

But since you asked for the user I'm trying to fecth I tested my code with "robertdowneyjr" and... it's working fine !
For privacy concerns I don't want to post the user I'm trying to fetch but do you have any ideas on what could be the problem ?
Because on my test server I can fetch getMoreMedias fine with this user so it's not that there is nothing to fetch.

**Comment by xsindesign** [comment]
I figured out what was the problem !
Turns out the production server (shared host) is a 32bit system (...yeah it's still a thing), which means that casting a string to an int is limited to a "2147483647" number (per PHP manual).
And since the ID of an instagram user can go above that : "Houston we have a problem".
Problem can be solved by not type hinting or casting to int anything related to the user id.

**Comment by pgrimaud** [comment]
@xsindesign Good catch. Yes It's the problem.

> Problem can be solved by not type hinting or casting to int anything related to the user id.

Or just catch to float? What do you think about it?

```php
echo (int) '8554104470'; // 2147483647
echo (float) '8554104470'; // 8554104470
```

**Comment by xsindesign** [comment]
I've mixed feeling about casting to a float since it's an id and we don't do maths with it, I think it's just ok if it's treated as a string.
But that's just me, in the end both should work fine.

**Comment by pgrimaud** [comment]
> I've mixed feeling about casting to a float since it's an id and we don't do maths with it, I think it's just ok if it's treated as a string.

Yeah was a bad idea. 🤠 

But casting it to a string may cause BC to users (e.g. me, in my apps) because of strict type.
Today `$profile->getId();` should return an int. I will add a new method `getIdFor32Bits();`.

I'm working on a way to manage this, properly. (Set a flag to the API : force 32bit or something like that 🤔)

**Comment by xsindesign** [comment]
You can eventually test if PHP_INT_SIZE = 4 (32bits and 8 for 64bits) then call the appropriate function to handle the id.

**Comment by pgrimaud** [comment]
Good idea, I released 6.3.1, could you try with this version?

**Comment by xsindesign** [comment]
Fatal error: Uncaught TypeError: Return value of Instagram\Model\Profile::getId32Bit() must be of the type string, null returned.

**Comment by pgrimaud** [comment]
@xsindesign What if you're running examples/medias.php ?

**Comment by xsindesign** [comment]
Sorry my bad, it is working with getMoreMedias() !
The error is with using getMoreMediasWithCursor()

**Comment by pgrimaud** [comment]
Are you using `getMoreMediasWithCursor()`? If not, I will not add 32bit support into this method.

**Comment by xsindesign** [comment]
In fact no, I used it at some point in an attempt to figure out my problem.
