### ISSUE TITLE
[Enhancement] getProfileById('12345')

### ISSUE THREAD

**Issue by eldark** [pgrimaud/instagram-user-feed#79]
Hi there, @pgrimaud !
I moved from **instagram-php-scraper** to your api today. So far, it's been working GREAT.
I have an enhancement request, which is the ability to fetch user profiles from their ID. This is great for when an Username changes. This way, if it fails you can get the Profile by it's ID and update the username column.

**Comment by pgrimaud** [comment]
Sure, I will take a look at it tomorrow.

You only need to fetch user profiles from their ID? Not medias? Only profile data?

**Comment by eldark** [comment]
It might be useful if that method extended getProfile($username). So I wouldn't need three calls in case username changed:

1. Fetch profile by username. Username does not exist.
2. Fetch profile by Id. Update the username.
3. Fetch profile by new username.

That would be replaced by:

1. Fetch profile by Id.

In this case, the username just would be used to describe the media parsed.

**Comment by pgrimaud** [comment]
@eldark I added a method getProfileById in the version 6.2.4 👍 

You can check the example here : https://github.com/pgrimaud/instagram-user-feed/blob/6.2.4/examples/profile-by-id.php
