### ISSUE TITLE
symfony/cache problem

### ISSUE THREAD

**Issue by tonyellow** [pgrimaud/instagram-user-feed#80]
I have the same problem like this user, but with another version of symfony/cache.:
Using version ^6.2 for pgrimaud/instagram-user-feed
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pgrimaud/instagram-user-feed 6.2.2 requires symfony/cache ^3.4|^4.4|^5.0 -> no matching package found.
    - pgrimaud/instagram-user-feed 6.2.1 requires symfony/cache ^4.4|^5.0 -> no matching package found.
    - pgrimaud/instagram-user-feed 6.2.0 requires symfony/cache ^5.0 -> no matching package found.
    - Installation request for pgrimaud/instagram-user-feed ^6.2 -> satisfiable by pgrimaud/instagram-user-feed[6.2.0, 6.2.1, 6.2.2].

I have symfony/cache version v4.3.11.
What can I do to solve?

_Originally posted by @tonyellow in https://github.com/pgrimaud/instagram-user-feed/issues/74#issuecomment-640202720_

**Comment by pgrimaud** [comment]
Hello @tonyellow 

I allow symfony/cache constrain to ^4.3. Please upgrade to 6.2.3
It should work now 😄

**Comment by tonyellow** [comment]
Thanks a lot, I can confirm it works now.
