### ISSUE TITLE
Login multiple times on form with 2 steps

### ISSUE THREAD

**Issue by vietel** [pgrimaud/instagram-user-feed#81]
Hi everybody, 

I have a form with 2 steps as follows (on 2 pages):

Step 1: submit username with input field (the purpose is to check the existence of the username)
Step 2: get the image from profile that submited above

Do I have to use the code below at every step?

`     $api-> login ($username, $password);
`

Is there any way to not have to log in multiple times?

Thank you so much

**Comment by pgrimaud** [comment]
Hello @vietel,

Yes you have to login each time you instantiate the package.

But, after the first login, session cookies are stored into cache driver.
Then this data cached are used to each next Instagram calls. (https://github.com/pgrimaud/instagram-user-feed/blob/6.x/src/Instagram/Api.php#L60)

> Do I have to use the code below at every step?
> 
> ` $api-> login ($username, $password);`

Yes, but in fact, you really login to Instagram 1 time. (https://github.com/pgrimaud/instagram-user-feed/blob/6.x/src/Instagram/Api.php#L74, when cookies into cache driver are empty)

**Comment by vietel** [comment]
Thank you for the explanation,

In your opinion, should you set the time for session cookies or leave the default?

I mean: should I reset a session cookies after a specific time (eg.1 hour)?

**Comment by pgrimaud** [comment]
> In your opinion, should you set the time for session cookies or leave the default?

Just to be clear, the instagram session is not shared with default PHP session. Instagram session is stored with cache driver.

The Instagram session is valid for... **1 YEAR**. So in theory, using a cache driver and one account will trigger only one real login to Instagram then reusing session for a long time.

I used this package on one of my website, with a script which only retrieve new medias 4 times per day. The session stored in the cache driver (FS here) is the same since the 22nd of May 2020.

> I mean: should I reset a session cookies after a specific time (eg.1 hour)?

Nope 😉

**Comment by vietel** [comment]
Thank you for the useful information.

Today I had another problem with the **getLogin ()** function.

[02-Jul-2020 17:13:09 UTC] PHP Fatal error: Uncaught Error: Call to a member function getLogin () on boolean in /var/www/html/include/step-2.php:53

			try {
			    $instagram = new Api($cachePool);
			    _$instagram->login($credentials->getLogin(), $credentials->getPassword());_  **--> LINE 53** 


Look forward to the help.

Thanks

**Comment by pgrimaud** [comment]
@vietel Weird...

You also could try this :

```php
$instagram = new Api($cachePool);
$instagram->login('instagramLogin', 'instagramPassword');
```

The credentials.php file was an example using an anonymous class : fast way for example, not the best for production.

**Comment by vietel** [comment]
Thank you @pgrimaud
