### ISSUE TITLE
checkpoint_required

### ISSUE THREAD

**Issue by drneamati** [pgrimaud/instagram-user-feed#84]
Can integrate Instagram with your package , that no need to Login by php code?
for example , I already logged in my instagram account on my browser.so your code just read the user feed without need to log in to my instagram again by Login method?

**Comment by pgrimaud** [comment]
Hi @drneamati 

There is no bridge between your browser and the PHP code.

This package simulates login directly with the PHP code, and save cookies (session) it into a cache adapter (Filesystem in example). 
Then it reuses data from cookies to simulate a real user navigation.
