### ISSUE TITLE
cache should be optional in version 6

### ISSUE THREAD

**Issue by smknstd** [pgrimaud/instagram-user-feed#86]
what do you think ?

**Comment by pgrimaud** [comment]
Hi @smknstd 

The cache is mandatory to save cookies (session) to simulate "real" requests to Instagram.
They improve their bot detection and without real session data in the headers requests, you IP could be easily soft-ban by Instagram. And you can't fetch more than 48 medias without login.

**Comment by smknstd** [comment]
Good to know, maybe you could add this kind of information to the README.

**Comment by pgrimaud** [comment]
> Good to know, maybe you could add this kind of information to the README.

Sure, I'll do this 👍
