### ISSUE TITLE
Getting error message 'Instagram blocked you IP' after using for sometime.

### ISSUE THREAD

**Issue by skumar25dec** [pgrimaud/instagram-user-feed#87]
Getting error message 'Instagram blocked you IP' after using for sometime. 

Do we have any work around to avoid ip getting blocked?

**Comment by pgrimaud** [comment]
Hi @skumar25dec 
I guess you're using v5.x

Could you upgrade to v6.x, adapt your code and try again?

**Comment by gaeld** [comment]
Hi, 

Might be related.
I'm have the following error with 6.0 : 
`PHP Fatal error:  Uncaught Instagram\Exception\InstagramAuthException: Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response:
{"message": "", "spam": true, "status": "fail"}`

How to change that ?
Thanks !

**Comment by pgrimaud** [comment]
@gaeld 429 error is "Too Many Requests"

Are you using multiple accounts in your app? If yes, how many?

**Comment by skumar25dec** [comment]
So far we are not getting any IP blocked message with version 6.2.

Is there a way to get mp4 url as well with media for video content?

**Comment by gaeld** [comment]
@pgrimaud Thanks ! 
I'm not, it's a single account, single app. I'm just using it to fecth last photos of the feed.

**Comment by pgrimaud** [comment]
@gaeld Are you on a shared hosting? Could you try to login to your Instagram account in your browser?

**Comment by gaeld** [comment]
@pgrimaud It's a shared hosting. I can connect no pblm in web brower, and in security, I have no record of the hosting trying to connect.

Is there a known solution ?

**Comment by pgrimaud** [comment]
> @pgrimaud It's a shared hosting. I can connect no pblm in web brower, and in security, I have no record of the hosting trying to connect.
> 
> Is there a known solution ?

I have never been faced with this problem before.

Did you try with another Instagram account? We will exclude if it's an IP ban or account ban.

**Comment by Nisthar** [comment]
@pgrimaud so instagram blocks you if you use multiple ips for a single acc?

**Comment by pgrimaud** [comment]
> @pgrimaud so instagram blocks you if you use multiple ips for a single acc?

I have not experienced this before, and not one have report this.

But Instagram may block you if you use a tons (have not the exact numbers) of Instagram accounts on the same IP. It happened on some shared hosting with multiple Instagram crawlers.

**Comment by Nisthar** [comment]
@pgrimaud ok it makes sense. if they did, they would have to ban ppl using vpns.

**Comment by camohub** [comment]
I have the same error from version 6.6 right now. On localhost it works ok. But as I stroe it to production server it throws me this error.
[2020-11-06 14:00:37] development.ERROR: Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response:
{"message": "", "spam": true, "status": "fail"}

**Comment by viniciusao** [comment]
> > @pgrimaud so instagram blocks you if you use multiple ips for a single acc?
> 
> I have not experienced this before, and not one have report this.
> 
> But Instagram may block you if you use a tons (have not the exact numbers) of Instagram accounts on the same IP. It happened on some shared hosting with multiple Instagram crawlers.

I do web scraping (selenium webdriver) some insta photos to get quantity of likes and comments, after ~2k photos I get "spam":true and have to switch accounts.

**Comment by akzsbombsrs** [comment]
Man my instagram is showin try again later 
{"message":"","spam":true,"status":"fail"}
What does this mean

**Comment by viniciusao** [comment]
> Man my instagram is showin try again later
> {"message":"","spam":true,"status":"fail"}
> What does this mean

it does means that instagram thinks you are spamming their servers, hence, you won't be able to get info for a while, be careful to not lose the acc.

**Comment by akzsbombsrs** [comment]
Okay thanks

**Comment by krishhhnaaaaaaa** [comment]
I am not a scammer

**Comment by stanleykin** [comment]
Hi my account got blocked and I didn't know why pls anyone help

**Comment by sawan5258** [comment]
I am not a scammer please recover My account please please recover my account please i am not a scammer please 🥺

**Comment by mulieoo** [comment]
How do I fix {"message":"","status":"fail"} in Instagram ??

**Comment by Akpan988** [comment]
How do l fix this  {"message":"","status":"fail"} in Instagram ??
