### ISSUE TITLE
How can I use proxies with multi account?

### ISSUE THREAD

**Issue by vietel** [pgrimaud/instagram-user-feed#89]
Hi everybody

Instagram can lock or restrict login at any time.

So I want to use multiple accounts in combination with proxies.

Suppose, I have the following proxies:

> 1.1.1.1
> 2.2.2.2
> 3.3.3.3
> 4.4.4.4

And the following Instagram accounts: [[USERNAME / PASSWORD]]

> instaguser1 / passwd
> instaguser2 / passwd
> instaguser3 / passwd
> instaguser4 / passwd

_All accounts have the same password (_**passwd**_)._

@pgrimaud 
How can I use proxies in combination with accounts in credentials.php file (**examples** folder)

Thank you so much !

**Comment by pgrimaud** [comment]
First, I allow to save in cache multiple instagram sessions : https://github.com/pgrimaud/instagram-user-feed/commit/3acdcd172d4ea743fb2b3455ccfa9af50b922f8f (previously it was not possible, only one session was saved in cache).

Then I added an example for using proxies here : https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/using-proxies.php

```php
$client = new Client([
    'proxy' => [
        'https' => '91.209.25.156:8080'
    ]
]);

$api = new Api($cachePool, $client);
$api->login('login', 'password');

// do what you want with this proxy and this instagram account
```

Then you just have to implement you own strategy to :
- use proxy1 with instaguser1 account
- use proxy2 with instaguser2 account
- etc.

**Comment by vietel** [comment]
Thanks for your support.

Is there a way to declare proxy in credentials.php file? (Then, each login time, use the variable <$proxy> to call the proxy)

ex:
```
$client = new Client([
    'proxy' => [
        'https' => **$proxy**
    ]
]);

$api = new Api($cachePool, $client);
$api->login('login', 'password');
```

**Comment by pgrimaud** [comment]
The credentials file is modular. I created it only for the examples, so you cant change it without any problem.

**Comment by vietel** [comment]
On version 6.3, it works very well.

Thank you very much @pgrimaud
