### ISSUE TITLE
Cannot access private property

### ISSUE THREAD

**Issue by clubmagic87** [pgrimaud/instagram-user-feed#94]
I cannot get Medias after I have updated the new version.
Someone help me fix this issue.

```
$api = new Api($cachePool);
$api->login($usernamex,$passwordx);
$feed = $api->getProfile('robertdowneyjr');
print_r($feed->userName);
```
Fatal error: Uncaught Error: Cannot access private property Instagram\Model\Profile::$userName 
Error: Cannot access private property Instagram\Model\Profile::$userName

**Comment by clubmagic87** [comment]
@pgrimaud Do you know about this issue?

**Comment by David-Kurniawan** [comment]
@clubmagic87 read the examples please https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/profile.php

the codes should be like:
`$profile->getUserName()`

**Comment by clubmagic87** [comment]
I want to get full Medias. Not only username :(

**Comment by David-Kurniawan** [comment]
then just follow this example:
https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/medias.php

```php
$api = new Api($cachePool);
$api->login($usernamex,$passwordx);
$feed = $api->getProfile('robertdowneyjr');
print_r($feed->getMedias());
```

**Comment by clubmagic87** [comment]
@David-Kurniawan How can I get "displaySrc" in Medias?

**Comment by pgrimaud** [comment]
@clubmagic87 You can fetch displaySrc with this method : https://github.com/pgrimaud/instagram-user-feed/blob/master/src/Instagram/Model/Media.php#L207

```php
$api = new Api($cachePool);
$api->login($usernamex,$passwordx);
$feed = $api->getProfile('robertdowneyjr');

print_r($feed->getMedias()[0]->getDisplaySrc();
```

**Comment by clubmagic87** [comment]
Thanks. I got it.
