### ISSUE TITLE
Fetching less than 48 medias without login on version 6

### ISSUE THREAD

**Issue by smknstd** [pgrimaud/instagram-user-feed#95]
> And you can't fetch more than 48 medias without login.

When using the library for fetching last ~10 posts of a given account once a day, if I understand well it would be technically possible to do it without login but credentials are mandatory in version 6. It would be great to make it possible without any credentials. What do you think ?

**Comment by pgrimaud** [comment]
> When using the library for fetching last ~10 posts of a given account once a day, if I understand well it would be technically possible to do it without login but credentials are mandatory in version 6. It would be great to make it possible without any credentials. What do you think ?

It's technically possible if you're on a dedicated hosted (not shared).
But Instagram is fighting against bots, and they could change it at any moment.

What's the problem about login, for you? You just have to create a dummy account.

**Comment by smknstd** [comment]
Ok but maybe you cloud explian a bit in readme why you chose to made login mandatory.
