### ISSUE TITLE
All contributors bot

### ISSUE THREAD

**Issue by pgrimaud** [pgrimaud/instagram-user-feed#96]

**Comment by pgrimaud** [comment]
@all-contributors please add @pgrimaud for code

**Comment by pgrimaud** [comment]
@all-contributors please add @jannejava for code

**Comment by pgrimaud** [comment]
@all-contributors please add @cookieguru for code

**Comment by pgrimaud** [comment]
@all-contributors please add @Dlinny for bug

**Comment by pgrimaud** [comment]
@all-contributors please add @renedekat for bug

**Comment by pgrimaud** [comment]
@all-contributors please add @renedekat for bug

**Comment by pgrimaud** [comment]
@all-contributors please add @ikiselev1989 for bug

**Comment by pgrimaud** [comment]
@all-contributors please add @Pezhvak for code

**Comment by pgrimaud** [comment]
@all-contributors please add @bytehead for code

**Comment by pgrimaud** [comment]
@all-contributors please add @kumamidori fir code

**Comment by Pezhvak** [comment]
hey @pgrimaud, what's the plan?
